### ISSUE TITLE
OSError: [Errno 26] Text file busy

### ISSUE THREAD

**Issue by barakova** [fenderglass/ABruijn#130]
Hi,

I have just started to assemble bacterial strains from my first MinION run. In the polishing step I get the error OSError: [Errno 26] Text file busy: '/media/sf_BioLinux-vymena_dat/Run1_part_data/BC03_CT224/Flye_output/40-polishing/edges_aln.sam'. Can you please advice me what went wrong? It happened in all three strains I have tried.

Here is what my terminal showed me:
manager@bl8vbox[BC03_CT224] flye --nano-raw FAK*.fastq --plasmids --meta -g 5.1000m -o ./Flye_output -t 4                                                                                          [12:04PM]
[2019-06-26 12:06:22] INFO: Starting Flye 2.4.2-release
[2019-06-26 12:06:22] INFO: >>>STAGE: configure
[2019-06-26 12:06:22] INFO: Configuring run
[2019-06-26 12:06:28] INFO: Total read length: 184186173
[2019-06-26 12:06:28] INFO: Input genome size: 5100000
[2019-06-26 12:06:28] INFO: Estimated coverage: 36
[2019-06-26 12:06:28] INFO: Reads N50/N90: 16378 / 4911
[2019-06-26 12:06:28] INFO: Minimum overlap set to 5000
[2019-06-26 12:06:28] INFO: Selected k-mer size: 15
[2019-06-26 12:06:28] INFO: >>>STAGE: assembly
[2019-06-26 12:06:28] INFO: Assembling disjointigs
[2019-06-26 12:06:28] INFO: Reading sequences
[2019-06-26 12:06:31] INFO: Generating solid k-mer index
[2019-06-26 12:06:46] INFO: Counting k-mers (1/2):
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 
[2019-06-26 12:06:55] INFO: Counting k-mers (2/2):
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 
[2019-06-26 12:07:16] INFO: Filling index table (1/2)
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 
[2019-06-26 12:07:48] INFO: Filling index table (2/2)
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 
[2019-06-26 12:08:23] INFO: Extending reads
[2019-06-26 12:08:42] INFO: Overlap-based coverage: 28
[2019-06-26 12:08:42] INFO: Median overlap divergence: 0.115347
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 
[2019-06-26 12:09:06] INFO: Assembled 4 disjointigs
[2019-06-26 12:09:06] INFO: Generating sequence
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 
[2019-06-26 12:10:41] INFO: >>>STAGE: consensus
[2019-06-26 12:10:42] INFO: Running Minimap2
[2019-06-26 12:11:57] INFO: Computing consensus
[2019-06-26 12:14:56] INFO: Alignment error rate: 0.133751920882
[2019-06-26 12:14:56] INFO: >>>STAGE: repeat
[2019-06-26 12:14:56] INFO: Building and resolving repeat graph
[2019-06-26 12:14:56] INFO: Reading sequences
[2019-06-26 12:15:00] INFO: Building repeat graph
10% 20% 30% 50% 60% 70% 80% 100% 
[2019-06-26 12:15:23] INFO: Median overlap divergence: 0.0718023
[2019-06-26 12:15:23] INFO: Aligning reads to the graph
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 
[2019-06-26 12:16:12] INFO: Aligned read sequence: 163854881 / 165275396 (0.991405)
[2019-06-26 12:16:12] INFO: Median overlap divergence: 0.0433
[2019-06-26 12:16:12] INFO: Mean edge coverage: 33
[2019-06-26 12:16:12] INFO: Resolving repeats
[2019-06-26 12:16:13] INFO: >>>STAGE: plasmids
[2019-06-26 12:16:13] INFO: Recovering short unassembled sequences
[2019-06-26 12:16:47] INFO: Added 0 extra contigs
[2019-06-26 12:16:48] INFO: >>>STAGE: contigger
[2019-06-26 12:16:48] INFO: Generating contigs
[2019-06-26 12:16:48] INFO: Reading sequences
[2019-06-26 12:16:51] INFO: Generated 2 contigs
[2019-06-26 12:16:51] INFO: >>>STAGE: polishing
[2019-06-26 12:16:51] INFO: Polishing genome (1/1)
[2019-06-26 12:16:52] INFO: Running minimap2
[2019-06-26 12:18:02] INFO: Separating alignment into bubbles
[2019-06-26 12:21:48] INFO: Alignment error rate: 0.0864054167236
[2019-06-26 12:21:48] INFO: Correcting bubbles
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 
Traceback (most recent call last):
  File "/usr/local/bin/flye", line 31, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/flye/main.py", line 745, in main
    _run(args)
  File "/usr/local/lib/python2.7/dist-packages/flye/main.py", line 555, in _run
    jobs[i].run()
  File "/usr/local/lib/python2.7/dist-packages/flye/main.py", line 365, in run
    self.args.threads)
  File "/usr/local/lib/python2.7/dist-packages/flye/polishing/polish.py", line 204, in generate_polished_edges
    os.remove(alignment_file)
OSError: [Errno 26] Text file busy: '/media/sf_BioLinux-vymena_dat/Run1_part_data/BC03_CT224/Flye_output/40-polishing/edges_aln.sam'

Thank you

(included flye log)
[flye.log](https://github.com/fenderglass/Flye/files/3330290/flye.log)

**Comment by mikolmogorov** [comment]
Hi,

What OS are you using? It seems like it thinks that the file handle was not properly - maybe it depends on a particular Python implementation.

I've pushed a change to the `flye` (main) branch - I think it should fix it for you. Let me know if it worked.

Mikhail

**Comment by barakova** [comment]
Hi,

I am using BioLinux on my VirtualMachine as I am very new to this. I plan to switch to normal Ubuntu on VM soon.

Unfortunately when running the same sample again it made the same error. I hope I have updated correctly (_git pull_ and then _python setup.py build_).

Thank you,

Alzbeta

**Comment by mikolmogorov** [comment]
Hi,

The update command is correct. Looks like the problem might be specific to this particular BioLinux build (no one else reported any similar issues before).

Since you are planning to switch to Ubuntu, let's wait and see if it works there (it should). Let me know how it goes.

Mikhail

**Comment by mikolmogorov** [comment]
Closing due to inactivity, feel free to reopen if the problem remains.
