### ISSUE TITLE
IOError: [Errno 5] Input/output error

### ISSUE THREAD

**Issue by HTaekOppa** [fenderglass/ABruijn#147]
Hi Flye,

I tested Flye 2.4.2-release to assemble plant genome (3Gb), but I encountered a IOError (please see attached file for log file).

2019-09-03 05:25:44] INFO: Generated 4173 contigs
[2019-09-03 05:41:27] INFO: >>>STAGE: polishing
[2019-09-03 05:41:27] INFO: Polishing genome (1/2)
[2019-09-03 05:42:16] INFO: Running minimap2
[2019-09-03 14:57:18] INFO: Separating alignment into bubbles
Traceback (most recent call last):
  File "/work/waterhouse_team/miniconda2/envs/flye/bin/flye", line 31, in <module>
    sys.exit(main())
  File "/work/waterhouse_team/miniconda2/envs/flye/lib/python2.7/site-packages/flye/main.py", line 731, in main
    _run(args)
  File "/work/waterhouse_team/miniconda2/envs/flye/lib/python2.7/site-packages/flye/main.py", line 541, in _run
    jobs[i].run()
  File "/work/waterhouse_team/miniconda2/envs/flye/lib/python2.7/site-packages/flye/main.py", line 344, in run
    output_progress=True)
  File "/work/waterhouse_team/miniconda2/envs/flye/lib/python2.7/site-packages/flye/polishing/polish.py", line 93, in polish
    bubbles_file)
  File "/work/waterhouse_team/miniconda2/envs/flye/lib/python2.7/site-packages/flye/polishing/bubbles.py", line 90, in make_bubbles
    cfg.vals["max_read_coverage"])
  File "/work/waterhouse_team/miniconda2/envs/flye/lib/python2.7/site-packages/flye/polishing/alignment.py", line 103, in __init__
    for line in f:
IOError: [Errno 5] Input/output error

Below is an executed command
-----
PBS Job 4901501.pbs
CPU time  : 3317:33:54
Wall time : 118:04:30
Mem usage : 894482040kb

#PBS -N FyA_QLD
#PBS -l walltime=150:00:00
#PBS -j oe
#PBS -l mem=1000G
#PBS -l ncpus=36

cd $PBS_O_WORKDIR

conda activate flye

flye --pacbio-raw /work/QLD_ONT_PB8_All.fastq --genome-size 3000m  --out-dir QLD_FlyeA --threads 36 --iterations 2

conda deactivate

Any advice would be appreciated! 

Best regards,

Taek
[QLD_FlyeA.zip](https://github.com/fenderglass/Flye/files/3567867/QLD_FlyeA.zip)

**Comment by mikolmogorov** [comment]
Hi Taek,

Please try the latest Flye 2.5, it should resolve the issue. You can resume the existing run with `--resume-from polishing`

Mikhail

**Comment by HTaekOppa** [comment]
Hi Mikhail,

Have tried as you suggested.
And this time I have encountered another error as below:

[2019-09-05 18:23:36] INFO: Starting Flye 2.5-release
[2019-09-05 18:23:36] INFO: Resuming previous run
[2019-09-05 18:23:36] INFO: >>>STAGE: polishing
[2019-09-05 18:23:36] INFO: Polishing genome (1/2)
[2019-09-05 18:24:24] INFO: Running minimap2
[2019-09-05 23:57:29] INFO: Separating alignment into bubbles
[2019-09-06 01:55:13] INFO: Alignment error rate: 0.164894129199
[2019-09-06 01:55:13] INFO: Correcting bubbles
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
[2019-09-06 09:10:12] INFO: Polishing genome (2/2)
[2019-09-06 09:11:01] INFO: Running minimap2
/var/spool/PBS/mom_priv/jobs/4936957.pbs.SC: line 15: 29792 Bus error               (core dumped) flye --pacbio-raw /work/waterhouse_team/All_RawData/Benth/PacBio_gDNA/QLD_PacBio_April_2019/NbQLD_All8.fastq --genome-size 3000m --resume-from polishing --out-dir NbQLD_FlyeB --threads 36 --iterations 2

-----
PBS Job 4936957.pbs
CPU time  : 524:10:57
Wall time : 21:16:15
Mem usage : 536540884kb


And the flye.log file says as below (last 50 lines):

[2019-09-04 18:46:48] DEBUG: Final graph contiain 6440 egdes
[2019-09-04 18:46:48] DEBUG: Extending contigs into repeats
[2019-09-04 18:47:41] DEBUG: Covered 2312 repetitive contigs
[2019-09-04 18:47:41] INFO: Generated 4136 contigs
[2019-09-04 18:47:41] DEBUG: Writing FASTA
[2019-09-04 18:48:14] DEBUG: Generating scaffold connections
[2019-09-04 19:01:35] DEBUG: Writing Dot
[2019-09-04 19:02:18] DEBUG: Writing FASTA
[2019-09-04 19:03:32] DEBUG: Writing Gfa
[2019-09-04 19:04:42] DEBUG: Peak RAM usage: 66 Gb
-----------End assembly log------------
[2019-09-04 19:05:27] root: INFO: >>>STAGE: polishing
[2019-09-04 19:05:28] root: INFO: Polishing genome (1/2)
[2019-09-04 19:06:23] root: INFO: Running minimap2
[2019-09-05 18:23:36] root: INFO: Starting Flye 2.5-release
[2019-09-05 18:23:36] root: DEBUG: Cmd: /work/waterhouse_team/miniconda2/envs/flye/bin/flye --pacbio-raw /work/waterhouse_team/All_RawData/Benth/PacBio_gDNA/QLD_PacBio_April_2019/NbQLD_All8.fastq --genome-size 3000m --resume-from polishing --out-dir NbQLD_FlyeB --threads 36 --iterations 2
[2019-09-05 18:23:36] root: INFO: Resuming previous run
[2019-09-05 18:23:36] root: INFO: >>>STAGE: polishing
[2019-09-05 18:23:36] root: INFO: Polishing genome (1/2)
[2019-09-05 18:24:24] root: INFO: Running minimap2
[2019-09-05 23:57:29] root: INFO: Separating alignment into bubbles
[2019-09-06 01:55:12] root: DEBUG: Generated 95290273 bubbles
[2019-09-06 01:55:12] root: DEBUG: Split 8513 long bubbles
[2019-09-06 01:55:12] root: DEBUG: Skipped 860 empty bubbles
[2019-09-06 01:55:12] root: DEBUG: Skipped 82 bubbles with long branches
[2019-09-06 01:55:13] root: INFO: Alignment error rate: 0.164894129199
[2019-09-06 01:55:13] root: INFO: Correcting bubbles
[2019-09-06 09:10:12] root: INFO: Polishing genome (2/2)
[2019-09-06 09:11:01] root: INFO: Running minimap2


Despite this, I have found these files in 40-polishing folder:

-rw-rw---- 1 jungh2 default 2.7G Sep  6 09:09 polished_1.fasta
-rw-rw---- 1 jungh2 default 469G Sep  6 14:55 minimap_2.sam_sorted
-rw-rw---- 1 jungh2 default 212K Sep  6 13:31 minimap_2.sam_merged
-rw-rw---- 1 jungh2 default 2.7G Sep  6 09:11 chunks_2.fasta


By any chance, is the "polished_1.fasta" final outcome? 


While the manual says: the main output files are "assembly.fasta", "assembly_graph.gfa" and "assembly_info.txt",  I am not able to see/fine these files.

Did I miss something?

Cheers,

Taek

**Comment by mikolmogorov** [comment]
Hi Taek,

I think it might be that you ran out of disk space - the alignment size if ~500Gb, and you need roughly as much (temporarily) to process it.

That said, the first polishing iteration has finished successfully. You can use the following command to generate the final assembly using the results from the first iteration:
`/work/waterhouse_team/miniconda2/envs/flye/bin/flye --pacbio-raw /work/waterhouse_team/All_RawData/Benth/PacBio_gDNA/QLD_PacBio_April_2019/NbQLD_All8.fastq --genome-size 3000m --out-dir NbQLD_FlyeB --threads 36 --iterations 1 --resume-from finalize`

Once you have the final assembly, you can add more iterations using `--polish-target` option.

**Comment by HTaekOppa** [comment]
Hi again,

I have tried but there was no luck. 

Executed script: 
/work/waterhouse_team/miniconda2/envs/flye/bin/flye --pacbio-raw /work/waterhouse_team/All_RawData/Benth/PacBio_gDNA/QLD_PacBio_April_2019/NbQLD_All8.fastq --genome-size 3000m --out-dir NbQLD_FlyeB --threads 24 --iterations 1 --resume-from finalize

[2019-09-15 21:02:42] INFO: Starting Flye 2.5-release
[2019-09-15 21:02:42] INFO: Resuming previous run
[2019-09-15 21:02:42] INFO: >>>STAGE: polishing
[2019-09-15 21:02:42] INFO: Polishing genome (1/2)
[2019-09-15 21:03:25] INFO: Running minimap2
[2019-09-16 02:29:05] ERROR: Command '['flye-minimap2', '/lustre/scratch/waterhouse_team/Taek_Test/QLD_Assemblies/Flye_QLD/NbQLD_FlyeB/NbQLD_FlyeB/40-polishing/chunks_1.fasta', '/work/waterhouse_team/All_RawData/Benth/PacBio_gDNA/QLD_PacBio_April_2019/NbQLD_All8.fastq', '-x', 'map-pb', '-t', '20', '-a', '-p', '0.7', '-N', '10']' returned non-zero exit status -11

-----
PBS Job 4974339.pbs
CPU time  : 100:14:12
Wall time : 05:27:20
Mem usage : 38256024kb


Executed script:
flye --pacbio-raw /work/waterhouse_team/All_RawData/Benth/PacBio_gDNA/QLD_PacBio_April_2019/NbQLD_All8.fastq --genome-size 3000m --out-dir NbQLD_FlyeB --threads 20 --iterations 2 --resume-from polishing

[2019-09-29 10:34:02] INFO: Starting Flye 2.5-release
[2019-09-29 10:34:02] INFO: Resuming previous run
[2019-09-29 10:34:02] INFO: >>>STAGE: polishing
[2019-09-29 10:34:02] INFO: Polishing genome (1/2)
[2019-09-29 10:34:51] INFO: Running minimap2
[2019-09-29 17:35:58] ERROR: Command '['flye-minimap2', '/lustre/scratch/waterhouse_team/Taek_Test/QLD_Assemblies/Flye_QLD/NbQLD_FlyeB/NbQLD_FlyeB/40-polishing/chunks_1.fasta', '/work/waterhouse_team/All_RawData/Benth/PacBio_gDNA/QLD_PacBio_April_2019/NbQLD_All8.fastq', '-x', 'map-pb', '-t', '20', '-a', '-p', '0.7', '-N', '10']' returned non-zero exit status -11

-----
PBS Job 4974627.pbs
CPU time  : 107:28:53
Wall time : 07:05:37
Mem usage : 36204920kb

Any suggestion?

Regards,

Taek

**Comment by mikolmogorov** [comment]
Hi Taek,

The first command with `--resume-from finalize` can't produce this output - it should have resumed from finalize stage (and generate the final assembly). Are you sure this is the correct command line that was executed?

Have you also verified that you have sufficient space? E.g. `df -h` should tell you how much is left on each filesystem.

**Comment by HTaekOppa** [comment]
Hi again,

Re space issue, it should not be any program about the space because it is unlimited (literally). 

Some reason why one of my data has been worked with this command (Flye 2.5):

flye --pacbio-raw /work/waterhouse_team/All_RawData/Benth/PacBio_gDNA/QLD_PacBio_April_2019/QLD_ONT_PB8_All.fastq --genome-size 3000m  --out-dir NbQLD_FlyeA --threads 20 --iterations 2 --resume-from polishing

However, the same command did not work for the other data with this error:

[2019-10-11 08:33:56] INFO: Starting Flye 2.5-release
[2019-10-11 08:33:56] INFO: Resuming previous run
[2019-10-11 08:33:56] INFO: >>>STAGE: polishing
[2019-10-11 08:33:56] INFO: Polishing genome (1/2)
[2019-10-11 08:34:40] INFO: Running minimap2
[2019-10-11 14:00:29] ERROR: Command '['flye-minimap2', '/lustre/scratch/waterhouse_team/Taek_Test/QLD_Assemblies/Flye_QLD/NbQLD_FlyeB/NbQLD_FlyeB/40-polishing/chunks_1.fasta', '/work/waterhouse_team/All_RawData/Benth/PacBio_gDNA/QLD_PacBio_April_2019/NbQLD_All8.fastq', '-x', 'map-pb', '-t', '20', '-a', '-p', '0.7', '-N', '10']' returned non-zero exit status -11

-----
PBS Job 5020875.pbs
CPU time  : 99:49:08
Wall time : 05:30:40
Mem usage : 38291472kb


Even after updating the version (Flye 2.6), it also has generated this error:
[2019-10-11 15:40:29] INFO: Starting Flye 2.6-release
[2019-10-11 15:40:29] INFO: Resuming previous run
[2019-10-11 15:40:30] INFO: >>>STAGE: polishing
[2019-10-11 15:40:30] INFO: Polishing genome (1/2)
[2019-10-11 15:41:13] INFO: Running minimap2
[2019-10-11 22:35:08] INFO: Separating alignment into bubbles
[2019-10-12 01:34:40] INFO: Alignment error rate: 0.164894
[2019-10-12 01:34:40] INFO: Correcting bubbles
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
[2019-10-12 13:51:01] INFO: Polishing genome (2/2)
[2019-10-12 13:51:49] INFO: Running minimap2
[2019-10-12 19:50:15] INFO: Separating alignment into bubbles
[2019-10-12 20:33:23] INFO: Starting Flye 2.6-release
[2019-10-12 20:33:23] INFO: Resuming previous run
[2019-10-12 20:33:23] INFO: >>>STAGE: polishing
[2019-10-12 20:33:23] INFO: Polishing genome (1/2)
[2019-10-12 20:34:06] INFO: Running minimap2
[2019-10-13 02:06:46] ERROR: Command '['flye-minimap2', '/lustre/scratch/waterhouse_team/Taek_Test/QLD_Assemblies/Flye_QLD/NbQLD_FlyeB/NbQLD_FlyeB/40-polishing/chunks_1.fasta', '/work/waterhouse_team/All_RawData/Benth/PacBio_gDNA/QLD_PacBio_April_2019/NbQLD_All8.fastq', '-x', 'map-pb', '-t', '20', '-a', '-p', '0.7', '-N', '10']' returned non-zero exit status -11

-----
PBS Job 5023502.pbs
CPU time  : 101:25:25
Wall time : 05:33:47
Mem usage : 37527900kb


Now I am testing again from the scratch using Flye2.6 and will keep you informed.

Regards,

Taek

**Comment by mikolmogorov** [comment]
Hi Taek,

It seems that multiple users are experiencing a similar problem with minimap2 crashes. I am working on debugging this, but it seems that the crashes are not deterministic. Make sure that the server is not overloaded (e.g. you are not requesting more threads that are currently available) and try the same command again.

I propose to continue the discussion in #152 so everyone can track the progress on this issue. Please keep us informed.

Mikhail
