### ISSUE TITLE
Fail to install

### ISSUE THREAD

**Issue by Chandrima-04** [fenderglass/ABruijn#208]
Hi, 
There is some issues occuring while installation:

```
Traceback (most recent call last):
  File "setup.py", line 38, in run
    subprocess.check_call(["make"])
  File "/home/miniconda3/envs/py35/lib/python3.5/subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make']' returned non-zero exit status 2

Traceback (most recent call last):
  File "setup.py", line 80, in <module>
    'install' : MakeInstall}
  File "/home/miniconda3/envs/py35/lib/python3.5/site-packages/setuptools/__init__.py", line 140, in setup
    return distutils.core.setup(**attrs)
  File "/home/miniconda3/envs/py35/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/miniconda3/envs/py35/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/miniconda3/envs/py35/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 45, in run
    SetuptoolsInstall.run(self)
  File "/home/miniconda3/envs/py35/lib/python3.5/site-packages/setuptools/command/install.py", line 65, in run
    orig.install.run(self)
  File "/home/miniconda3/envs/py35/lib/python3.5/distutils/command/install.py", line 539, in run
    self.run_command('build')
  File "/home/miniconda3/envs/py35/lib/python3.5/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/miniconda3/envs/py35/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 40, in run
    sys.exit("Compilation error: ", e)
TypeError: exit expected at most 1 arguments, got 2
```

**Comment by mikolmogorov** [comment]
Hi,

Looks like you don't have the developer environment in your system. This error says there is no `make` program, which typically comes with GCC compilers. Please refer to INSTALL.md for the build requirements, or alternatively use bioconda builds.
