### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '~/assembly_graph.gv'

### ISSUE THREAD

**Issue by xvtyzn** [fenderglass/ABruijn#223]
Hi,

First of all, thank you for creating this excellent software.

Now I'm assembling the genomes of marine organisms, estimated to be around 800 Mbp using nanopore sequences. 

```
flye --nano-raw long.fq --genome-size 765m  --out-dir otter -t 70
```

I got an error in the final stage (finalize stage) of flye version 2.6 (Python3). However, there were no confirmed Permission issues. I suspect it's a problem due to shutil.copy2.

```
[2020-02-21 16:41:51] INFO: >>>STAGE: polishing
[2020-02-21 16:41:51] INFO: Polishing genome (1/1)
[2020-02-21 16:42:09] INFO: Running minimap2
[2020-02-21 18:02:00] INFO: Separating alignment into bubbles
[2020-02-21 18:38:11] INFO: Alignment error rate: 0.099622
[2020-02-21 18:38:11] INFO: Correcting bubbles
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
[2020-02-21 21:00:36] INFO: >>>STAGE: finalize
Traceback (most recent call last):
  File "/home/ide/miniconda3/envs/masurca/bin/flye", line 11, in <module>
    load_entry_point('flye==2.6', 'console_scripts', 'flye')()
  File "/home/ide/miniconda3/envs/masurca/lib/python3.6/site-packages/flye/main.py", line 764, in main
    _run(args)
  File "/home/ide/miniconda3/envs/masurca/lib/python3.6/site-packages/flye/main.py", line 566, in _run
    jobs[i].run()
  File "/home/ide/miniconda3/envs/masurca/lib/python3.6/site-packages/flye/main.py", line 267, in run
    shutil.copy2(self.graph_file, self.out_files["graph"])
  File "/home/ide/miniconda3/envs/masurca/lib/python3.6/shutil.py", line 258, in copy2
    copystat(src, dst, follow_symlinks=follow_symlinks)
  File "/home/ide/miniconda3/envs/masurca/lib/python3.6/shutil.py", line 225, in copystat
    _copyxattr(src, dst, follow_symlinks=follow)
  File "/home/ide/miniconda3/envs/masurca/lib/python3.6/shutil.py", line 165, in _copyxattr
    os.setxattr(dst, name, value, follow_symlinks=follow_symlinks)
PermissionError: [Errno 13] Permission denied: '/home/ide/Shijimi/flye/otter/assembly_graph.gv'
```

Do you have any solutions?

Thanks.

Keigo

**Comment by xvtyzn** [comment]
Additional information.
It is not clear if this is a common problem, but the error was resolved when main.py changed line 267-268 from

```
        shutil.copy2(self.graph_file, self.out_files["graph"])
        shutil.copy2(self.polished_gfa, self.out_files["gfa"])
```
to
```
        shutil.copy(self.graph_file, self.out_files["graph"])
        shutil.copy(self.polished_gfa, self.out_files["gfa"])
```

 However, I do not know if this is the right solution.

**Comment by mikolmogorov** [comment]
@xvtyzn Thanks for reporting this. Will look more into that - never saw this error occurring before.
