### ISSUE TITLE
flye-minimap2 installation error

### ISSUE THREAD

**Issue by MichelMoser** [fenderglass/ABruijn#226]
Hi, 

While compiling from source,  i run into an error during minimap2 installation. 

GNU Make 4.3
gcc version 7.3.0
Python 3.6.7 

Thank you, 
Michel

```
cc -c -g -Wall -O2 -Wc++-compat  -DHAVE_KALLOC  pe.c -o pe.o
cc -c -g -Wall -O2 -Wc++-compat  -DHAVE_KALLOC  esterr.c -o esterr.o
cc -c -g -Wall -O2 -Wc++-compat  -DHAVE_KALLOC  splitidx.c -o splitidx.o
cc -c -g -Wall -O2 -Wc++-compat  -msse2 -DHAVE_KALLOC  ksw2_ll_sse.c -o ksw2_ll_sse.o
cc -c -g -Wall -O2 -Wc++-compat  -msse4.1 -DHAVE_KALLOC -DKSW_CPU_DISPATCH  ksw2_extz2_sse.c -o ksw2_extz2_sse41.o
cc -c -g -Wall -O2 -Wc++-compat  -msse4.1 -DHAVE_KALLOC -DKSW_CPU_DISPATCH  ksw2_extd2_sse.c -o ksw2_extd2_sse41.o
cc -c -g -Wall -O2 -Wc++-compat  -msse4.1 -DHAVE_KALLOC -DKSW_CPU_DISPATCH  ksw2_exts2_sse.c -o ksw2_exts2_sse41.o
cc -c -g -Wall -O2 -Wc++-compat  -msse2 -mno-sse4.1 -DHAVE_KALLOC -DKSW_CPU_DISPATCH -DKSW_SSE2_ONLY  ksw2_extz2_sse.c -o ksw2_extz2_sse2.o
cc -c -g -Wall -O2 -Wc++-compat  -msse2 -mno-sse4.1 -DHAVE_KALLOC -DKSW_CPU_DISPATCH -DKSW_SSE2_ONLY  ksw2_extd2_sse.c -o ksw2_extd2_sse2.o
cc -c -g -Wall -O2 -Wc++-compat  -msse2 -mno-sse4.1 -DHAVE_KALLOC -DKSW_CPU_DISPATCH -DKSW_SSE2_ONLY  ksw2_exts2_sse.c -o ksw2_exts2_sse2.o
cc -c -g -Wall -O2 -Wc++-compat  -msse4.1 -DHAVE_KALLOC -DKSW_CPU_DISPATCH  ksw2_dispatch.c -o ksw2_dispatch.o
ar -csru libminimap2.a kthread.o kalloc.o misc.o bseq.o sketch.o sdust.o options.o index.o chain.o align.o hit.o map.o format.o pe.o esterr.o splitidx.o ksw2_ll_sse.o ksw2_extz2_sse41.o ksw2_extd2_sse41.o ksw2_exts2_sse41.o ksw2_extz2_ss
e2.o ksw2_extd2_sse2.o ksw2_exts2_sse2.o ksw2_dispatch.o
cc -g -Wall -O2 -Wc++-compat  main.o -o minimap2 -L. -lminimap2 -lm -lz -lpthread
/net/fs-1/projects01/Orion/various/local/genome/packages/anaconda3/latest/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: cannot find -lz
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:36: minimap2] Error 1
make[1]: Leaving directory '/net/fs-1/home01/michelmo/tools/Flye/lib/minimap2'
make: *** [Makefile:18: /net/fs-1/home01/michelmo/tools/Flye/bin/flye-minimap2] Error 2
make: *** [Makefile:18: /net/fs-1/home01/michelmo/tools/Flye/bin/flye-minimap2] Error 2                                                                                                                                              [0/1925]
Traceback (most recent call last):
  File "setup.py", line 38, in run
    subprocess.check_call(["make"])
  File "/local/genome/packages/anaconda3/latest/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make']' returned non-zero exit status 2.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 80, in <module>
    'install' : MakeInstall}
  File "/local/genome/packages/anaconda3/latest/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/local/genome/packages/anaconda3/latest/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/local/genome/packages/anaconda3/latest/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/local/genome/packages/anaconda3/latest/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 45, in run
    SetuptoolsInstall.run(self)
  File "/local/genome/packages/anaconda3/latest/lib/python3.6/site-packages/setuptools/command/install.py", line 65, in run
    orig.install.run(self)
  File "/local/genome/packages/anaconda3/latest/lib/python3.6/distutils/command/install.py", line 545, in run
    self.run_command('build')
  File "/local/genome/packages/anaconda3/latest/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/local/genome/packages/anaconda3/latest/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 40, in run
    sys.exit("Compilation error: ", e)
TypeError: exit expected at most 1 arguments, got 2
```

**Comment by mikolmogorov** [comment]
Hi,

You are missing the development headers for zlib.

Mikhail
