### ISSUE TITLE
Crashed at stage: plasmids 

### ISSUE THREAD

**Issue by hzhengsh** [fenderglass/ABruijn#229]
Hi there,

I got an error during the plasmids stage. The command has been run like this (Flye version is 2.7b-b1527): 

    nohup flye --plasmids --meta --pacbio-corr m64019_190804_121838.subreads.fmlrc.fasta -g 0.6g -o metaflye -t 60 -i 2 -m 2000 &

Log file is too big (~100MB). Error returned as below.:

[2020-03-03 17:53:17] INFO: >>>STAGE: plasmids
[2020-03-03 17:53:17] INFO: Recovering short unassembled sequences
[2020-03-03 21:22:34] INFO: Added 865 extra contigs
Traceback (most recent call last):
  File "/dartfs-hpc/rc/home/j/f003c6j/lab_space/software/Flye/bin/flye", line 25, in <module>
    sys.exit(main())
  File "/dartfs/rc/lab/L/Labofoz/hzhengsh/software/Flye/flye/main.py", line 771, in main
    _run(args)
  File "/dartfs/rc/lab/L/Labofoz/hzhengsh/software/Flye/flye/main.py", line 567, in _run
    jobs[i].run()
  File "/dartfs/rc/lab/L/Labofoz/hzhengsh/software/Flye/flye/main.py", line 156, in run
    repeat_graph.load_from_file(self.repeat_graph)
  File "/dartfs/rc/lab/L/Labofoz/hzhengsh/software/Flye/flye/repeat_graph/repeat_graph.py", line 138, in load_from_file
    self_complement, resolved, mean_coverage, alt_group) = tokens[1:]
ValueError: not enough values to unpack (expected 8, got 7)

Do you have any idea with this.

Any suggestions will be appreciated!

**Comment by mikolmogorov** [comment]
Hi,

Looks like an inconsistency between Python and C++ parts of Flye. Please try the latest code and make sure that you are performing a clean build. Or use the recent bioconda release.

Mikhail
