### ISSUE TITLE
Issues with minimap2 alignment during consensus stage

### ISSUE THREAD

**Issue by yangxiaofeill** [fenderglass/ABruijn#291]
Dear author,
Thanks for the good assembler.
I am trying assembly a human genome using flye based on 30x CLR data. However, I got such errors:

```
[2020-07-23 21:29:35] DEBUG: Ovlp index size: 22802138
[2020-07-23 21:29:35] DEBUG: Inner: 5664162 covered: 11118820 total: 11118820
[2020-07-23 21:29:37] INFO: Assembled 4306 disjointigs
[2020-07-23 21:35:48] INFO: Generating sequence
[2020-07-24 01:01:38] DEBUG: Writing FASTA
[2020-07-24 01:02:06] DEBUG: Peak RAM usage: 656 Gb
-----------End assembly log------------
[2020-07-24 01:03:50] root: DEBUG: Disjointigs length: 3279037350, N50: 18086005
[2020-07-24 01:03:50] root: INFO: >>>STAGE: consensus
[2020-07-24 01:04:46] root: INFO: Running Minimap2
[2020-07-28 10:16:05] root: INFO: Starting Flye 2.7-b1585
[2020-07-28 10:16:05] root: DEBUG: Cmd: flye --pacbio-raw CLR_1.fastq.gz CLR_2.fastq.gz --genome-size 3.1g --thread 20 --resume --out-dir clr_flye
[2020-07-28 10:16:05] root: DEBUG: Python version: 3.7.7 (default, May  7 2020, 21:25:33) 
[GCC 7.3.0]
[2020-07-28 10:16:05] root: INFO: Resuming previous run
[2020-07-28 10:16:06] root: INFO: >>>STAGE: consensus
[2020-07-28 10:37:26] root: INFO: Running Minimap2
[2020-07-30 19:49:37] root: ERROR: Error running minimap2, terminating. See the alignment error log  for details: clr_flye/10-consensus/minimap.stderr
[2020-07-30 19:49:37] root: ERROR: Command '['/bin/bash', '-c', 'set -o pipefail; flye-minimap2 /clr_flye/10-consensus/chunks.fasta CLR_1.fastq.gz CLR_2.fastq.gz -x map-pb -t 20 -a -p 0.5 -N 10 --sam-hit-only -L -Q --secondary-seq | flye-samtools view -T clr_flye/10-consensus/chunks.fasta -u - | flye-samtools sort -T clr_flye/10-consensus/sort_200728_103726 -O bam -@ 4 -l 1 -m 4G']' returned non-zero exit status 1.
[2020-07-30 19:49:37] root: ERROR: Pipeline aborted
```

I checked the `alignment error log` file, and got

```
[M::worker_pipeline::27318.086*8.10] mapped 27559 sequences
[M::worker_pipeline::27366.233*8.12] mapped 28009 sequences
[M::worker_pipeline::27414.467*8.14] mapped 27728 sequences
[W::sam_read1] Parse error at line 11831680
[main_samview] truncated file.
[bam_sort_core] merging from 80 files and 1 in-memory blocks...
```

The output files are like:

```
drwxrwxr-x 1 xfyang xfyang 3.1G July  24 01:01 00-assembly
drwxrwxr-x 1 xfyang xfyang 140G July  30 19:50 10-consensus
-rw-rw-r-- 1 xfyang xfyang 1.8M July  30 19:50 flye.log
-rw-rw-r-- 1 xfyang xfyang  110 July 28 10:16 params.json
```

Do you have any idea for such errors? Thanks very much.

Best
Xiaofei

**Comment by mikolmogorov** [comment]
Hi,

Do you have the terminal output for that? From what I see, looks similar to #152, #237 - e.g. unsolved problem in minimap2. Could you restart the run (`--resume-from consensus`) and check if it fails again? Also, make sure you have sufficient disk space (e.g. 300Gb+).

**Comment by yangxiaofeill** [comment]
Hi, 
The terminal output looks like:

```
[2020-07-28 10:16:05] INFO: Starting Flye 2.7-b1585
[2020-07-28 10:16:05] INFO: Resuming previous run
[2020-07-28 10:16:06] INFO: >>>STAGE: consensus
[2020-07-28 10:37:26] INFO: Running Minimap2
[2020-07-30 19:49:37] ERROR: Error running minimap2, terminating. See the alignment error log  for details: /home/xfyang/HBV_CLR_assembly/clr_flye/10-consensus/minimap.stderr
[2020-07-30 19:49:37] ERROR: Command '['/bin/bash', '-c', 'set -o pipefail; flye-minimap2 ./clr_flye/10-consensus/chunks.fasta SNU387_1.fastq.gz SNU387_2.fastq.gz -x map-pb -t 20 -a -p 0.5 -N 10 --sam-hit-only -L -Q --secondary-seq | flye-samtools view -T ./clr_flye/10-consensus/chunks.fasta -u - | flye-samtools sort -T ./clr_flye/10-consensus/sort_200728_103726 -O bam -@ 4 -l 1 -m 4G']' returned non-zero exit status 1.
[2020-07-30 19:49:37] ERROR: Pipeline aborted
Exception in thread "main" java.lang.RuntimeException: Input file does not appear to be valid: assembly.fasta
        at jgi.AssemblyStats2.process(AssemblyStats2.java:244)
        at jgi.AssemblyStats2.main(AssemblyStats2.java:38)
```

I will try to run by parameter `--resume-from consensus` to check if it fails again. If there are some results, I will feedback to you.

Best
Xiaofei

**Comment by jelber2** [comment]
I had gotten this error as well at some point. I am not sure if it is a shell environment thing or not as the command works that gives the error if manually entered on a Ubuntu 16.04 computer. I didn’t try to troubleshoot further using Flye 2.7.1 I think.

**Comment by jdmontenegro** [comment]
hello everyone,

I just got this error for the first time ever using flye2.7. I had never seen it before. Interestingly, it only happened in 1 out of 10 assemblies, but the error was reproducible and happened at the same point.
I am testing if this error is propagated into the new release 2.8. I will come back with more information.

BTW, there is a known error in the main branch of minimap2 that appear to be a conflict with slurm. Heng Li especulated that it may have something to do with the slurm scheduling and that would cause a bad memory allocation at a random position in the faile and the segfault which would produce a truncated sam file. As far as I know, this has not been solved yet. Check it out here: https://github.com/lh3/minimap2/issues/570

Best regards,

Juan D. Montenegro

**Comment by yangxiaofeill** [comment]
@fenderglass  Hi Author,
I tried parameter `--resume-from consensus`, however, the error still occures.

```
[2020-08-07 21:14:01] INFO: Starting Flye 2.7-b1585
[2020-08-07 21:14:01] INFO: Resuming previous run
[2020-08-07 21:14:01] INFO: >>>STAGE: consensus
[2020-08-07 21:15:59] INFO: Running Minimap2
[2020-08-08 13:36:51] ERROR: Error running minimap2, terminating. See the alignment error log  for details: ./ont_flye/10-consensus/minimap.stderr
```

I also checkec the `minimap.stderr` file,  the output like:

```
[M::main] Version: 2.17-r941
[M::main] CMD: flye-minimap2 -x map-ont -t 50 -a -p 0.5 -N 10 --sam-hit-only -L -Q --secondary-seq ./ont_flye/10-consensus/chunks.fasta  $theFqlist 
[M::main] Real time: 36658.500 sec; CPU: 821214.104 sec; Peak RSS: 46.847 GB
[bam_sort_core] merging from 340 files and 4 in-memory blocks...
```

Fro this results, I think minimap2 donot have errors.  I also checked files in `10-consensus` folder, and found  

```
-rw-rw-r-- 1 xfyang xfyang   3328868303 Aug   7 21:16 chunks.fasta
-rw-rw-r-- 1 xfyang xfyang       242462 Aug  5 19:48 chunks.fasta.fai
-rw-rw-r-- 1 xfyang xfyang 344012256152 Aug   8 13:37 minimap.bam
-rw-rw-r-- 1 xfyang xfyang        96349 Aug  8 07:27 minimap.stderr
-rw-rw-r-- 1 xfyang xfyang   1035181558 Aug   5 19:56 sort_200805_194724.0000.bam
-rw-rw-r-- 1 xfyang xfyang   1049506814 Aug   5 19:56 sort_200805_194724.0001.bam
-rw-rw-r-- 1 xfyang xfyang   1063122963 Aug   5 19:56 sort_200805_194724.0002.bam
-rw-rw-r-- 1 xfyang xfyang   1044775910 Aug   5 19:56 sort_200805_194724.0003.bam
-rw-rw-r-- 1 xfyang xfyang   1044365583 Aug   5 20:02 sort_200805_194724.0004.bam
-rw-rw-r-- 1 xfyang xfyang   1048660119 Aug   5 20:02 sort_200805_194724.0005.bam
-rw-rw-r-- 1 xfyang xfyang   1067180159 Aug   5 20:02 sort_200805_194724.0006.bam
-rw-rw-r-- 1 xfyang xfyang   1032556327 Aug  5 20:02 sort_200805_194724.0007.bam
-rw-rw-r-- 1 xfyang xfyang   1058657448 Aug   5 20:08 sort_200805_194724.0008.bam
-rw-rw-r-- 1 xfyang xfyang   1059394436 Aug  5 20:08 sort_200805_194724.0009.bam
......
```

Do you think there are errors in minimap2 step? And do you have any idea to solve it?

Best
Xiaofei

**Comment by mikolmogorov** [comment]
@yangxiaofeill thanks! Looks like the error happened in a different place now. Do you mind sending the full minimap.stderr file? But from what I see, looks like minimap2 exited without errors. In fact I don't see any reported errors in the log - and the size of minimap.bam roughly corresponds to what it should be.

Are you sure you are not running of disk space? Also note that you have old temporary *.bam files from the first run in 10-consensus, that should be manually deleted.

**Comment by yangxiaofeill** [comment]
@fenderglass  Yes, I am sure we have enough disk space. Attached is the minimap.stderr file, please check.

[minimap.stderr.txt](https://github.com/fenderglass/Flye/files/5055823/minimap.stderr.txt)

Can I delet the temporary bam file, e.g. the `sort_*.bam` manually? If I delet these files, I also want to resume flye, how to set the parameters?

Best
Xiaofei

**Comment by mikolmogorov** [comment]
@yangxiaofeill yes, please delete `sort_*.bam` files manually.

I looked though the log, but did not see anything suspicious - no sign of error. Is it a different run though - input read files look differently? 

Maybe try the following: 
(i) merge all fasta files into a single one (you have a lot, and theoretically you might be hitting command line length limit somehow). 
(ii) run the alignment command manually and see if it outputs any errors in terminal:
`flye-minimap2 ./clr_flye/10-consensus/chunks.fasta $READS -x map-pb -t 20 -a -p 0.5 -N 10 --sam-hit-only -L -Q --secondary-seq | flye-samtools view -T ./clr_flye/10-consensus/chunks.fasta -u - | flye-samtools sort -T ./clr_flye/10-consensus/sort_200728_103726 -O bam -@ 4 -l 1 -m 4G`. You may need to modify paths to flye-* binaries and consensus.fasta accordingly.
(iii) if it does error - please provide the terminal output. You can then try to run the same command with `-m 16G` instead of `-m 4G`

**Comment by yangxiaofeill** [comment]
@fenderglass , Thanks for your reply. I will try your suggestions.

Once there are results, I will tell you.

Best

**Comment by yangxiaofeill** [comment]
@fenderglass    
Thanks for your suggestions to merge all fastaq file into one file. It works, and my assembly is finished. Thanks.

Best
Xiaofei

**Comment by mikolmogorov** [comment]
@yangxiaofeill glad to hear, thanks!

**Comment by jdmontenegro** [comment]
Hi all, 
I am getting a similar error to this, but I already tried the solution above (merge all fastq files into a single file and rerun it), but failed all the same. with the error:

```
[2020-09-16 10:17:19] INFO: >>>STAGE: consensus
[2020-09-16 10:18:26] INFO: Running Minimap2
[2020-09-17 01:19:47] ERROR: Error running minimap2, terminating. See the alignment error log  for details: /scratch/pawsey0149/jdmontenegroc/zmays/results/asm/Flye/10-consensus/minimap.stderr
[2020-09-17 01:19:47] ERROR: Command '['/bin/bash', '-c', 'set -o pipefail; flye-minimap2 /scratch/pawsey0149/jdmontenegroc/zmays/results/asm/Flye/10-consensus/chunks.fasta /scratch/pawsey0149/jdmontenegroc/zmays/data/reads/all_reads.fastq -x map-pb -t 28 -a -p 0.5 -N 10 --sam-hit-only -L -Q --secondary-seq | flye-samtools view -T /scratch/pawsey0149/jdmontenegroc/zmays/results/asm/Flye/10-consensus/chunks.fasta -u - | flye-samtools sort -T /scratch/pawsey0149/jdmontenegroc/zmays/results/asm/Flye/10-consensus/sort_200916_101826 -O bam -@ 4 -l 1 -m 4G']' returned non-zero exit status 1.
[2020-09-17 01:19:47] ERROR: Pipeline aborted
srun: error: z115: task 0: Exited with exit code 1
```

when I look at the minimap.stderr I can see the following:

```
[M::mm_idx_gen::71.716*1.72] collected minimizers
[M::mm_idx_gen::79.647*2.13] sorted minimizers
[WARNING]^[[1;31m For a multi-part index, no @SQ lines will be outputted. Please use --split-prefix.^[[0m
[M::main::79.647*2.13] loaded/built the index for 27386 target sequence(s)
[M::mm_mapopt_update::82.634*2.08] mid_occ = 402
[M::mm_idx_stat] kmer size: 19; skip: 10; is_hpc: 1; #seq: 27386
[M::mm_idx_stat::85.760*2.05] distinct minimizers: 149301209 (45.70% are singletons); average occurrences: 3.458; average spacing: 7.773
[M::worker_pipeline::437.789*10.93] mapped 38756 sequences
[M::worker_pipeline::584.862*15.14] mapped 37128 sequences
...
[M::worker_pipeline::46019.755*26.85] mapped 35537 sequences
[M::worker_pipeline::46149.913*26.86] mapped 34604 sequences
[W::sam_read1] Parse error at line 73343156
[main_samview] truncated file.
[bam_sort_core] merging from 204 files and 4 in-memory blocks...

```
So it seems that it hits an error at line 73343156, but in the previous run it hit a similar parsing error at line 1252471, so it seems to be an issue with minimap, not the reads.

Any suggestions on how to resume the assembly?

Cheers,

Juan D. Montenegro

BTW, this is with flye 2.8

**Comment by mikolmogorov** [comment]
Looks like the same issue with minimap2 crash. Could you please run the following command manually and see if it finished successfully? Note that it is the same command line that crashed, but without `-N 10` option. You may need to adjust paths to flye-minimap and flye-samtools binaries.

`flye-minimap2 /scratch/pawsey0149/jdmontenegroc/zmays/results/asm/Flye/10-consensus/chunks.fasta /scratch/pawsey0149/jdmontenegroc/zmays/data/reads/all_reads.fastq -x map-pb -t 28 -a -p 0.5 --sam-hit-only -L -Q --secondary-seq | flye-samtools view -T /scratch/pawsey0149/jdmontenegroc/zmays/results/asm/Flye/10-consensus/chunks.fasta -u - | flye-samtools sort -T /scratch/pawsey0149/jdmontenegroc/zmays/results/asm/Flye/10-consensus/sort_200916_101826 -O bam -@ 4 -l 1 -m 4G`

**Comment by jdmontenegro** [comment]
Hi, 

Unfortunately it failed again:

```
[M::worker_pipeline::51689.535*25.57] mapped 38101 sequences
[M::worker_pipeline::51802.513*25.57] mapped 38426 sequences
[M::worker_pipeline::51912.669*25.57] mapped 37967 sequences
[M::worker_pipeline::52023.966*25.58] mapped 37974 sequences
[M::worker_pipeline::52135.781*25.58] mapped 37474 sequences
[M::worker_pipeline::52246.349*25.58] mapped 37508 sequences
[M::worker_pipeline::52407.940*25.57] mapped 38231 sequences
[M::worker_pipeline::52505.045*25.57] mapped 38858 sequences
[M::worker_pipeline::52621.632*25.57] mapped 38737 sequences
[M::worker_pipeline::52733.681*25.57] mapped 37821 sequences
[M::worker_pipeline::52843.883*25.58] mapped 38180 sequences
[M::worker_pipeline::52955.427*25.58] mapped 37745 sequences
srun: error: z119: task 0: Segmentation fault (core dumped)
[W::sam_read1] Parse error at line 76427783
[main_samview] truncated file.
[bam_sort_core] merging from 232 files and 4 in-memory blocks...
```

This time it failed at a different spot. As I mentioned before, I think there is a bug in minimap2 that makes it incompatible with slurm memory mapping. I could complete the alignment in a different computer without slurm, but it does not have nearly enough memory to continue the assembly. At assembly stage flye was using nearly 500GB of RAM. The other computer I have available only has 250GB. would it be possible to run only this mapping stage on a different computer and then resume the assembly in the slurm cluster?

Cheers,

Juan D.

**Comment by mikolmogorov** [comment]
Hi Juan,

Thanks for running the test - unfortunately indeed seems like a problem in minimap2 that you've mentioned..

Sure - you can copy the Flye working directory (and reads) to a different machine and resume the consensus stage using `--resume-from consensus`. Consensus stage does not need a lot of memory. It is also possible that you should be able to finish the rest of the assembly using 250Gb of RAM - so you would not need to copy the results for the second time.

Mikhail
