### ISSUE TITLE
Pipeline crashes on MacOS and Python >=3.8

### ISSUE THREAD

**Issue by vpylro** [fenderglass/ABruijn#300]
Hi!
I got the following error while trying to polish an assembly performed with canu.

flye --nano-corr /data/88a-oxford/88a.correctedReads.fasta --polish-target /data/88a-oxford/draft_genome.fa -o /data/polish

Any suggestions?

Many thanks in advance.

```victorpylro@Victors-MacBook-Pro ~ % flye --nano-corr /data/88a-oxford/88a.correctedReads.fasta --polish-target /data/88a-oxford/draft_genome.fa -o /data/polish -t 6 
[2020-09-10 20:54:25] INFO: Running Flye polisher
[2020-09-10 20:54:25] INFO: Polishing genome (1/1)
[2020-09-10 20:54:25] WARNING: Input contain non-ACGT characters - they will be converted to arbitrary ACGTs
[2020-09-10 20:54:25] INFO: Running minimap2
[2020-09-10 20:54:48] INFO: Separating alignment into bubbles
[2020-09-10 20:54:48] INFO: Running Flye polisher
[2020-09-10 20:54:48] INFO: Polishing genome (1/1)
[2020-09-10 20:54:48] WARNING: Input contain non-ACGT characters - they will be converted to arbitrary ACGTs
[2020-09-10 20:54:48] INFO: Running minimap2
[2020-09-10 20:55:13] INFO: Separating alignment into bubbles
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/victorpylro/anaconda3/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/victorpylro/anaconda3/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/victorpylro/anaconda3/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/victorpylro/anaconda3/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Users/victorpylro/anaconda3/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/victorpylro/anaconda3/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/victorpylro/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/victorpylro/tools/Flye/bin/flye", line 25, in <module>
    sys.exit(main())
  File "/Users/victorpylro/tools/Flye/flye/main.py", line 794, in main
    _run_polisher_only(args)
  File "/Users/victorpylro/tools/Flye/flye/main.py", line 516, in _run_polisher_only
    pol.polish(args.polish_target, args.reads, args.out_dir,
  File "/Users/victorpylro/tools/Flye/flye/polishing/polish.py", line 93, in polish
    make_bubbles(alignment_file, contigs_info, chunks_file,
  File "/Users/victorpylro/tools/Flye/flye/polishing/bubbles.py", line 92, in make_bubbles
    aln_reader = SynchronizedSamReader(alignment_path,
  File "/Users/victorpylro/tools/Flye/flye/utils/sam_parser.py", line 143, in __init__
    self.shared_manager = multiprocessing.Manager()
  File "/Users/victorpylro/anaconda3/lib/python3.8/multiprocessing/context.py", line 57, in Manager
    m.start()
  File "/Users/victorpylro/anaconda3/lib/python3.8/multiprocessing/managers.py", line 579, in start
    self._process.start()
  File "/Users/victorpylro/anaconda3/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/victorpylro/anaconda3/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
    return Popen(process_obj)
  File "/Users/victorpylro/anaconda3/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/victorpylro/anaconda3/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/victorpylro/anaconda3/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Users/victorpylro/anaconda3/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/Users/victorpylro/anaconda3/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "/Users/victorpylro/tools/Flye/bin/flye", line 25, in <module>
    sys.exit(main())
  File "/Users/victorpylro/tools/Flye/flye/main.py", line 794, in main
    _run_polisher_only(args)
  File "/Users/victorpylro/tools/Flye/flye/main.py", line 516, in _run_polisher_only
    pol.polish(args.polish_target, args.reads, args.out_dir,
  File "/Users/victorpylro/tools/Flye/flye/polishing/polish.py", line 93, in polish
    make_bubbles(alignment_file, contigs_info, chunks_file,
  File "/Users/victorpylro/tools/Flye/flye/polishing/bubbles.py", line 92, in make_bubbles
    aln_reader = SynchronizedSamReader(alignment_path,
  File "/Users/victorpylro/tools/Flye/flye/utils/sam_parser.py", line 143, in __init__
    self.shared_manager = multiprocessing.Manager()
  File "/Users/victorpylro/anaconda3/lib/python3.8/multiprocessing/context.py", line 57, in Manager
    m.start()
  File "/Users/victorpylro/anaconda3/lib/python3.8/multiprocessing/managers.py", line 583, in start
    self._address = reader.recv()
  File "/Users/victorpylro/anaconda3/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/Users/victorpylro/anaconda3/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/Users/victorpylro/anaconda3/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
```

**Comment by mikolmogorov** [comment]
Hi,

There is a recent issue with supporting Py3.8 on MacOS. I'd currently suggest to use any other python version <=3.7. You can also install Flye as a bioconda package - it should then pick a supported python release.

Mikhail

**Comment by vpylro** [comment]
Thanks. I have created a conda env with python 3.7 and then it worked.
Best,

**Comment by HAHasani** [comment]
Hi,
I'm getting this error as well & I tried installing flye with bioconda that didn't work, any idea how to fix it? I have long working pipeline that is working with my current setup...
Thanks

**Comment by mikolmogorov** [comment]
Which Flye and Python versions are using? Make sure Python version is 3.7. If it does not help, please post your log file.

**Comment by mikolmogorov** [comment]
This should now be fixed in the latest code in `flye` branch, and will be incorporated into the next release.
