### ISSUE TITLE
Pipeline crashes when no contigs were output at the repeat graph stage

### ISSUE THREAD

**Issue by schorlton** [fenderglass/ABruijn#317]
## Issue
Command:
```flye --nano-raw fail.fastq.gz --out-dir flye_test --threads 4 --plasmids --meta --keep-haplotypes --trestle```

Running with [fail.fastq.gz](https://github.com/fenderglass/Flye/files/5507256/fail.fastq.gz) errors with the output below. Running `flye 2.8`, installed with `conda`, inside of a docker container.

Thanks for your amazing work!

```
bash-4.4# flye --nano-raw fail.fastq.gz --out-dir flye_test --threads 4 --plasmids --meta --keep-haplotypes --trestle
[2020-11-08 20:22:24] INFO: Starting Flye 2.8-b1674
[2020-11-08 20:22:24] INFO: >>>STAGE: configure
[2020-11-08 20:22:24] INFO: Configuring run
[2020-11-08 20:22:25] INFO: Total read length: 30237471
[2020-11-08 20:22:25] INFO: Reads N50/N90: 5954 / 2701
[2020-11-08 20:22:25] INFO: Minimum overlap set to 3000
[2020-11-08 20:22:25] INFO: >>>STAGE: assembly
[2020-11-08 20:22:25] INFO: Assembling disjointigs
[2020-11-08 20:22:25] INFO: Reading sequences
[2020-11-08 20:22:30] INFO: Counting k-mers:
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 
[2020-11-08 20:23:44] INFO: Filling index table (1/2)
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 
[2020-11-08 20:23:48] INFO: Filling index table (2/2)
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 
[2020-11-08 20:23:53] INFO: Extending reads
[2020-11-08 20:23:55] INFO: Overlap-based coverage: 1
[2020-11-08 20:23:55] INFO: Median overlap divergence: 0.16487
0% 30% 100% 
[2020-11-08 20:24:01] INFO: Assembled 2 disjointigs
[2020-11-08 20:24:01] INFO: Generating sequence
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 
[2020-11-08 20:24:01] INFO: >>>STAGE: consensus
[2020-11-08 20:24:01] INFO: Running Minimap2
[2020-11-08 20:24:02] INFO: Computing consensus
[2020-11-08 20:24:03] INFO: Alignment error rate: 0.194717
[2020-11-08 20:24:03] INFO: >>>STAGE: repeat
[2020-11-08 20:24:03] INFO: Building and resolving repeat graph
[2020-11-08 20:24:03] INFO: Parsing disjointigs
[2020-11-08 20:24:03] INFO: Building repeat graph
0% 50% 100% 
[2020-11-08 20:24:03] INFO: Median overlap divergence: 0.162442
[2020-11-08 20:24:03] INFO: Parsing reads
[2020-11-08 20:24:03] INFO: Aligning reads to the graph
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 
[2020-11-08 20:24:07] INFO: Aligned read sequence: 86387 / 26339438 (0.00327976)
[2020-11-08 20:24:07] INFO: Median overlap divergence: 0.0938079
[2020-11-08 20:24:07] INFO: Mean edge coverage: 2
[2020-11-08 20:24:07] INFO: Simplifying the graph
[2020-11-08 20:24:07] INFO: >>>STAGE: trestle
[2020-11-08 20:24:07] INFO: Simple unbridged repeats: 0
[2020-11-08 20:24:07] INFO: Resolved: 0
[2020-11-08 20:24:07] INFO: >>>STAGE: plasmids
[2020-11-08 20:24:07] INFO: Recovering short unassembled sequences
[2020-11-08 20:24:15] INFO: Added 1 extra contigs
Traceback (most recent call last):
  File "/opt/conda/envs/bugseq/bin/flye", line 33, in <module>
    sys.exit(load_entry_point('flye==2.8', 'console_scripts', 'flye')())
  File "/opt/conda/envs/bugseq/lib/python3.7/site-packages/flye/main.py", line 785, in main
    _run(args)
  File "/opt/conda/envs/bugseq/lib/python3.7/site-packages/flye/main.py", line 571, in _run
    jobs[i].run()
  File "/opt/conda/envs/bugseq/lib/python3.7/site-packages/flye/main.py", line 157, in run
    plas.update_graph(repeat_graph, plasmids)
  File "/opt/conda/envs/bugseq/lib/python3.7/site-packages/flye/short_plasmids/plasmids.py", line 112, in update_graph
    new_edge_id = max(repeat_graph.edges.keys()) + 1
ValueError: max() arg is an empty sequence
```

**Comment by mikolmogorov** [comment]
Hi,

I suspect that no contigs were assembled as the result of the main pipeline, which somehow makes the plasmid assembly stage to fail. Please try running without `--plasmids` option to confirm. 30mb of reads is very unlikely to provide sufficient coverage for metagenome assembly, unfortunately.

Mikhail

**Comment by schorlton** [comment]
Running without `--plasmids` results in the following error:
```
[2020-11-15 17:02:28] INFO: Generated 0 contigs
[2020-11-15 17:02:28] INFO: >>>STAGE: polishing
[2020-11-15 17:02:28] INFO: Polishing genome (1/1)
[2020-11-15 17:02:28] INFO: Running minimap2
[2020-11-15 17:02:30] INFO: Separating alignment into bubbles
[2020-11-15 17:02:30] INFO: Alignment error rate: 0.000000
[2020-11-15 17:02:30] INFO: No reads were aligned during polishing
Traceback (most recent call last):
  File "/opt/conda/envs/bugseq/bin/flye", line 33, in <module>
    sys.exit(load_entry_point('flye==2.8', 'console_scripts', 'flye')())
  File "/opt/conda/envs/bugseq/lib/python3.7/site-packages/flye/main.py", line 785, in main
    _run(args)
  File "/opt/conda/envs/bugseq/lib/python3.7/site-packages/flye/main.py", line 571, in _run
    jobs[i].run()
  File "/opt/conda/envs/bugseq/lib/python3.7/site-packages/flye/main.py", line 367, in run
    self.out_files["stats"], self.out_files["contigs"])
  File "/opt/conda/envs/bugseq/lib/python3.7/site-packages/flye/polishing/polish.py", line 231, in filter_by_coverage
    mean_coverage = int(sum_cov / sum_length)
ZeroDivisionError: division by zero
```

I'm almost certain that you're right that it's just not enough data to assemble, I'm just wondering if any of these messages are true "errors" or if they're just uncaught "no contigs assembled, please submit more/better data"

**Comment by mikolmogorov** [comment]
@schorlton yes, you can see "0 contigs" in the top of the log file, so unfortunately nothing has been assembled. I indeed need to add a fix for catching this and outputting meaningful message instead of crashing.

**Comment by schorlton** [comment]
Thanks for being so quick and receptive @fenderglass!
