### ISSUE TITLE
OSError: [Errno 16] Device or resource busy

### ISSUE THREAD

**Issue by dcopetti** [fenderglass/ABruijn#328]
Hello,

During the Flye (v2.7.1) runs I get the following stdout message
During handling of the above exception, another exception occurred:
```
[...]
Traceback (most recent call last):
  File "/home/copettid/miniconda2/envs/flye_env/lib/python3.7/multiprocessing/util.py", line 277, in _run_finalizers
    finalizer()
  File "/home/copettid/miniconda2/envs/flye_env/lib/python3.7/multiprocessing/util.py", line 201, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/copettid/miniconda2/envs/flye_env/lib/python3.7/multiprocessing/util.py", line 110, in _remove_temp_dir
    rmtree(tempdir)
  File "/home/copettid/miniconda2/envs/flye_env/lib/python3.7/shutil.py", line 494, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/home/copettid/miniconda2/envs/flye_env/lib/python3.7/shutil.py", line 452, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/home/copettid/miniconda2/envs/flye_env/lib/python3.7/shutil.py", line 450, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
OSError: [Errno 16] Device or resource busy: '.nfs000000040018153f0000004f'
Traceback (most recent call last):
  File "/home/copettid/miniconda2/envs/flye_env/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/copettid/miniconda2/envs/flye_env/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/copettid/miniconda2/envs/flye_env/lib/python3.7/multiprocessing/managers.py", line 597, in _run_server
    server.serve_forever()
  File "/home/copettid/miniconda2/envs/flye_env/lib/python3.7/multiprocessing/managers.py", line 173, in serve_forever
    sys.exit(0)
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/copettid/miniconda2/envs/flye_env/lib/python3.7/multiprocessing/util.py", line 277, in _run_finalizers
    finalizer()
  File "/home/copettid/miniconda2/envs/flye_env/lib/python3.7/multiprocessing/util.py", line 201, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/copettid/miniconda2/envs/flye_env/lib/python3.7/multiprocessing/util.py", line 110, in _remove_temp_dir
    rmtree(tempdir)
  File "/home/copettid/miniconda2/envs/flye_env/lib/python3.7/shutil.py", line 494, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/home/copettid/miniconda2/envs/flye_env/lib/python3.7/shutil.py", line 452, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/home/copettid/miniconda2/envs/flye_env/lib/python3.7/shutil.py", line 450, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
OSError: [Errno 16] Device or resource busy: '.nfs00000004001813e400000050'
[2020-12-14 05:55:27] INFO: Alignment error rate: 0.126423
```

and a bunch of empty folders:
```
$ ls pymp-*
pymp-1moye2a4:

pymp-4vlec95h:

pymp-jfs4crzj:

pymp-qepf0jmn:

pymp-sn__6os1:

pymp-vhmykp0w:

```
I wonder if there is any relevant issue, I see that the job still continues and completes.
Thanks,
Dario

**Comment by mikolmogorov** [comment]
@dcopetti 

Thanks for reporting - have not seen this before. Looks like an error somewhere in the python multiprocessing library. There are several system threads that might have failed once all worker threads have finished and it seems that it indeed did not affect the result. 

So unless there will be any further complications with this run, or the error keeps reproducing in other runs - I don't see much reason to instigate it. 

Mikhail

**Comment by dcopetti** [comment]
It looks like we run out of space in the root directory of the virtual machine where the job was running - googling around I see that this could be the most likely cause
I will keep you posted if something changes
Thanks,
Dario

**Comment by daeunni** [comment]
@dcopetti  Hi, how did u address this problem? I have a same issue with u

**Comment by SvitlanaLukicheva** [comment]
I also have the same issue, with Flye 2.9.2-b1786.

**Comment by Maahi129** [comment]
Yes, it is space issue, clear space or else proceed with another working directory which has space.
Thank you.
