### ISSUE TITLE
SyntaxError: invalid & syntax sam_parser.py, line 136

### ISSUE THREAD

**Issue by JinqunHuang** [fenderglass/ABruijn#333]
Dear Mikhail,

I use Flye to assemble metagenomics Reads. My command was shown as below：

python /zfssz3/NASCT_BACKUP/MG01/huangjq3/HSZ09004-Verticillium.dahliae_Project/Software/Flye/bin/flye --pacbio-raw /zfssz3/BC_COM_P11/F16HTSNCKF1065/METmivM_HK/M0309-3MetaSample-map/METprrM_5MetaSample/HLD/1.Cleandata/HLD.filtered_subreads.fa --genome-size 377m --out-dir ./ --meta --threads 8

The subreads was produced by Sequel II.

![subreads](https://user-images.githubusercontent.com/47139043/103051572-291ac100-45d2-11eb-8894-42eafb3bd5c5.png)

But it runs to crash, would you please tell me how to fix it? Thanks a lot !

Traceback (most recent call last):
  File "/zfssz3/NASCT_BACKUP/MG01/huangjq3/HSZ09004-Verticillium.dahliae_Project/Software/Flye/bin/flye", line 24, in <module>
    from flye.main import main
  File "/zfssz3/NASCT_BACKUP/MG01/huangjq3/F18FTSNCKF1426-01-Verticillium.dahliae_Project/Software/Flye/flye/main.py", line 19, in <module>
    import flye.polishing.alignment as aln
  File "/zfssz3/NASCT_BACKUP/MG01/huangjq3/F18FTSNCKF1426-01-Verticillium.dahliae_Project/Software/Flye/flye/polishing/alignment.py", line 19, in <module>
    from flye.utils.sam_parser import AlignmentException
  File "/zfssz3/NASCT_BACKUP/MG01/huangjq3/F18FTSNCKF1426-01-Verticillium.dahliae_Project/Software/Flye/flye/utils/sam_parser.py", line 136
    for (h, s) in iteritems(reference_fasta)}
      ^
SyntaxError: invalid syntax

Best,
JinQun Huang

**Comment by JinqunHuang** [comment]
It seems that I did not set the python environment
