### ISSUE TITLE
Issue with Thread exceptions error

### ISSUE THREAD

**Issue by juefish** [fenderglass/ABruijn#365]
First off, thank you for the tool. We are very appreciative. 

Currently, we are exploring some low depth viral sequencing data and trying to use metaFlye to assemble it. When we run the pipeline, we get the following error:

0% [2021-03-05 14:46:35] DEBUG: Assembled disjointig 1
        With 7 reads
        Start read: +2e4367ff-2405-49de-8a29-8944f85edf6f
        At position: 5
        leftTip: 1 rightTip: 0
        Suspicious: 0
        Short ext: 0
        Mean extensions: 8
        Avg overlap len: 6383
        Min overlap len: 2613
        Inner reads: 0
        Length: 72752
[2021-03-05 14:46:35] DEBUG: Inner: 382 covered: 442 total: 956
40% 100%
[2021-03-05 14:46:36] INFO: Assembled 1 disjointigs
[2021-03-05 14:46:36] INFO: Generating sequence
0% 10% 30% 50% 60% 80% 100%
[2021-03-05 14:46:36] DEBUG: Writing FASTA
[2021-03-05 14:46:36] DEBUG: Peak RAM usage: 8 Gb
[2021-03-05 14:46:36] DEBUG: Disjointigs length: 72738, N50: 72738
[2021-03-05 14:46:36] INFO: >>>STAGE: consensus
[2021-03-05 14:46:36] INFO: Running Minimap2
[2021-03-05 14:46:36] INFO: Computing consensus
[2021-03-05 14:46:37] ERROR: Thread exception
[2021-03-05 14:46:37] ERROR: Traceback (most recent call last):
  File "/opt/Flye/flye/polishing/consensus.py", line 40, in _thread_worker
    ctg_id, ctg_aln = aln_reader.get_chunk()
  File "/opt/Flye/flye/utils/sam_parser.py", line 378, in get_chunk
    raise Exception("Error parsing SAM: record without read sequence")
Exception: Error parsing SAM: record without read sequence

[2021-03-05 14:46:38] ERROR: Thread exception
[2021-03-05 14:46:38] ERROR: Traceback (most recent call last):
  File "/opt/Flye/flye/polishing/consensus.py", line 45, in _thread_worker
    contigs_info[ctg_id].length)
KeyError: '*'

Traceback (most recent call last):
  File "/opt/Flye/bin/flye", line 25, in <module>
    sys.exit(main())
  File "/opt/Flye/flye/main.py", line 805, in main
    _run(args)
  File "/opt/Flye/flye/main.py", line 584, in _run
    jobs[i].run()
  File "/opt/Flye/flye/main.py", line 330, in run
    self.args.platform)
  File "/opt/Flye/flye/polishing/consensus.py", line 94, in get_consensus
    raise error_queue.get()
Exception: Error parsing SAM: record without read sequence

Any thoughts on what might be the issue. Log attached.

Regards,
Nate
[flye.log](https://github.com/fenderglass/Flye/files/6094026/flye.log)

**Comment by mikolmogorov** [comment]
Hi Nate,

It is likely that you have inconsistent versions of Python and C++ modules. A clean re-installation should solve it (don't forget to build with `make`). But I also highly recommend to use bioconda package, which will ensure all modules are synchronized.

**Comment by juefish** [comment]
Yup. You got it. I "make clean"-ed it and used updated devtoolset and python 3 to run setup.py build and setup.py install. Working fine now. Thanks!
