### ISSUE TITLE
Flye installation question

### ISSUE THREAD

**Issue by ranitori** [fenderglass/ABruijn#371]
Hi, I just installed Flye, and the Terminal output seemed OK except for a bunch of Warnings. Can I still run Flye confidently despite these warnings, or should I try and reinstall before using it?  Thanks.
Terminal output is attached.
System - MacBook Pro, Catalina OSX.
Installed from source:
git clone https://github.com/fenderglass/Flye
cd Flye
python setup.py install
[Flye_Install_Log.docx](https://github.com/fenderglass/Flye/files/6216728/Flye_Install_Log.docx)

**Comment by ranitori** [comment]
Hi again, as a follow-up, I just ran
python flye/tests/test_toy.py
and got the following output:

Running toy test:

[2021-03-27 19:00:59] INFO: Starting Flye 2.8.3-b1695
[2021-03-27 19:00:59] INFO: >>>STAGE: configure
[2021-03-27 19:00:59] INFO: Configuring run
[2021-03-27 19:00:59] INFO: Total read length: 8397200
[2021-03-27 19:00:59] INFO: Input genome size: 500000
[2021-03-27 19:00:59] INFO: Estimated coverage: 16
[2021-03-27 19:00:59] INFO: Reads N50/N90: 2700 / 1382
[2021-03-27 19:00:59] INFO: Selected minimum overlap: 1000
[2021-03-27 19:00:59] INFO: >>>STAGE: assembly
[2021-03-27 19:00:59] INFO: Assembling disjointigs
[2021-03-27 19:00:59] INFO: Reading sequences
[2021-03-27 19:00:59] INFO: Building minimizer index
[2021-03-27 19:00:59] INFO: Pre-calculating index storage
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 
[2021-03-27 19:01:01] INFO: Filling index
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 
[2021-03-27 19:01:05] INFO: Extending reads
[2021-03-27 19:01:11] INFO: Overlap-based coverage: 15
[2021-03-27 19:01:11] INFO: Median overlap divergence: 0.0187266
0% 10% 20% 30% 50% 60% 90% 100% 
[2021-03-27 19:01:13] INFO: Assembled 6 disjointigs
[2021-03-27 19:01:13] INFO: Generating sequence
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 
[2021-03-27 19:01:13] INFO: >>>STAGE: consensus
[2021-03-27 19:01:13] INFO: Running Minimap2
[2021-03-27 19:01:16] INFO: Computing consensus
Traceback (most recent call last):
  File "/Users/ranitori/miniconda3/bin/flye", line 33, in <module>
    sys.exit(load_entry_point('flye==2.8.3', 'console_scripts', 'flye')())
  File "/Users/ranitori/miniconda3/lib/python3.8/site-packages/flye/main.py", line 805, in main
    _run(args)
  File "/Users/ranitori/miniconda3/lib/python3.8/site-packages/flye/main.py", line 584, in _run
    jobs[i].run()
  File "/Users/ranitori/miniconda3/lib/python3.8/site-packages/flye/main.py", line 328, in run
    consensus_fasta = cons.get_consensus(out_alignment, chunks_file,
  File "/Users/ranitori/miniconda3/lib/python3.8/site-packages/flye/polishing/consensus.py", line 60, in get_consensus
    aln_reader = SynchronizedSamReader(alignment_path,
  File "/Users/ranitori/miniconda3/lib/python3.8/site-packages/flye/utils/sam_parser.py", line 160, in __init__
    self.io_thread.start()
  File "/Users/ranitori/miniconda3/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/ranitori/miniconda3/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/ranitori/miniconda3/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/ranitori/miniconda3/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/ranitori/miniconda3/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/ranitori/miniconda3/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Users/ranitori/miniconda3/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle 'weakref' object
Traceback (most recent call last):
  File "flye/tests/test_toy.py", line 41, in <module>
    sys.exit(main())
  File "flye/tests/test_toy.py", line 36, in main
    test_toy()
  File "flye/tests/test_toy.py", line 29, in test_toy
    subprocess.check_call(["flye", "--pacbio-corr", reads_file, "-g", "500k",
  File "/Users/ranitori/miniconda3/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['flye', '--pacbio-corr', '/Users/ranitori/Flye/flye/tests/data/ecoli_500kb_reads_hifi.fastq.gz', '-g', '500k', '-o', 'flye_toy_test', '-t', '8', '-m', '1000']' returned non-zero exit status 1.

**Comment by mikolmogorov** [comment]
Please see #300.
