### ISSUE TITLE
Computing Consensus hangs on certain dataset

### ISSUE THREAD

**Issue by ckeeling** [fenderglass/ABruijn#372]
Hello,

I have recently successfully used flye (2.8.3-b1695) to assemble several genomes, but one is giving me trouble. It always hangs at the computing consensus stage. I've repeated this three times, twice from the beginning, and once using --resume. The symptom is I notice that no files have been updated in many hours (24 h +). I look at what is going on at the compute node with top, and my only process running is my top command; there is one zombie process "[python3] \<defunct\>", and all the rest are sleeping. There are many of the following identical commands sleeping.

```bash
/cvmfs/soft.computecanada.ca/gentoo/2020/usr/lib/python-exec/python3.7/python3 /home/ckeeling/bin/Flye/bin/flye --nano-raw /localscratch/ckeeling.64835065.0/raw_nanopore.fastq.gz --out-dir /localscratch/ckeeling.64835065.0 --threads 48 --asm-coverage 100 --genome-size 323000000
```

And one of the following sleeping:
```bash
flye-samtools view -@4 /localscratch/ckeeling.64835065.0/10-consensus/minimap.bam
```

I am using one full compute node of 48 cpus and 187.50 GB RAM, using local compute node SSD storage. My command within a SLURM script is:
```bash
flye --nano-raw $SLURM_TMPDIR/raw_nanopore.fastq.gz --out-dir $SLURM_TMPDIR --threads 48 --asm-coverage 100  --genome-size 323000000
```

```bash
cat std.err
[2021-03-25 17:53:17] INFO: Starting Flye 2.8.3-b1695
[2021-03-25 17:53:17] INFO: >>>STAGE: configure
[2021-03-25 17:53:17] INFO: Configuring run
[2021-03-25 18:30:38] INFO: Total read length: 75254473523
[2021-03-25 18:30:38] INFO: Input genome size: 323000000
[2021-03-25 18:30:38] INFO: Estimated coverage: 232
[2021-03-25 18:30:38] INFO: Reads N50/N90: 8539 / 3481
[2021-03-25 18:30:38] INFO: Minimum overlap set to 3000
[2021-03-25 18:30:38] INFO: Using longest 100x reads for contig assembly
[2021-03-25 18:30:43] INFO: >>>STAGE: assembly
[2021-03-25 18:30:44] INFO: Assembling disjointigs
[2021-03-25 18:30:44] INFO: Reading sequences
[2021-03-25 18:59:03] INFO: Counting k-mers:
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 
[2021-03-25 19:15:06] INFO: Filling index table (1/2)
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 
[2021-03-25 19:24:57] INFO: Filling index table (2/2)
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 
[2021-03-25 19:37:30] INFO: Extending reads
[2021-03-25 19:46:29] INFO: Overlap-based coverage: 57
[2021-03-25 19:46:29] INFO: Median overlap divergence: 0.10723
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 
[2021-03-25 23:02:22] INFO: Assembled 2827 disjointigs
[2021-03-25 23:02:41] INFO: Generating sequence
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 
[2021-03-25 23:03:39] INFO: >>>STAGE: consensus
[2021-03-25 23:03:49] INFO: Running Minimap2
[2021-03-26 02:42:27] INFO: Computing consensus
```

The end of the flye.log is as follows:
```bash
...
[2021-03-25 23:01:43] DEBUG: Inner: 2979912 covered: 4774794 total: 4777086
[2021-03-25 23:01:51] DEBUG: Assembled disjointig 2827
	With 5 reads
	Start read: +e31c8f80-23a0-4a16-bbeb-4fbc8b64a6de
	At position: 4
	leftTip: 0 rightTip: 0
	Suspicious: 0
	Short ext: 0
	Mean extensions: 58
	Avg overlap len: 9674
	Min overlap len: 7099
	Inner reads: 0
	Length: 37025
[2021-03-25 23:01:51] DEBUG: Inner: 2979960 covered: 4775850 total: 4777086
[2021-03-25 23:02:22] INFO: Assembled 2827 disjointigs
[2021-03-25 23:02:41] INFO: Generating sequence
[2021-03-25 23:03:10] DEBUG: Writing FASTA
[2021-03-25 23:03:14] DEBUG: Peak RAM usage: 102 Gb
-----------End assembly log------------
[2021-03-25 23:03:39] root: DEBUG: Disjointigs length: 492459185, N50: 3419489
[2021-03-25 23:03:39] root: INFO: >>>STAGE: consensus
[2021-03-25 23:03:49] root: INFO: Running Minimap2
[2021-03-26 02:42:27] root: INFO: Computing consensus
```

The ```minimap.bam``` file in ```10-consensus``` was generated by Minimap2 (86G).

The job doesn't stop on its own, I cancel it. Any suggestions on what I can do to overcome this issue?

Thanks!

**Comment by mikolmogorov** [comment]
Hi,

Indeed seems like Flye hangs in the consensus stage for some reason. I have not seen this before, but my guess would be that there are some issues in Python's multiprocessing module. I'd suggest to try a different Python version, or Bioconda package (that ships its own Python version). Do toy examples from Usage document work for you?

Mikhail

**Comment by ckeeling** [comment]
Thanks for your quick response @fenderglass 

I am now trying a Singularity pull of a Docker flye container by @bschiffthaler with a different Python (3.8.7) and it has now finished the Computing consensus step and is on to the repeat stage.  Great! BTW, it was Python 3.7.7 that was problematic for me.

Cheers,
Chris

**Comment by kfuku52** [comment]
I encountered a similar situation with python 3.8.6 and flye 2.8.3: one zombie process + dozens of sleep processes without any progress for 24+ hours at the consensus stage. I'll try `--resume` and/or the docker container mentioned above.

### top
```
PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                           
 45324 kfuku     20   0  174088   4204   1700 R   1.0  0.0   0:00.31 top                                                                               
 33278 kfuku     20   0  177212   2428   1104 S   0.0  0.0   0:00.02 sshd                                                                              
 33285 kfuku     20   0  127948   4364   1800 S   0.0  0.0   0:00.10 bash                                                                              
 66104 kfuku     20   0   98.0g  80.6g      0 S   0.0 16.0  90:45.30 flye                                                                              
 66129 kfuku     20   0       0      0      0 Z   0.0  0.0  67:29.94 flye                                                                              
 66150 kfuku     20   0   18.1g 308272      0 S   0.0  0.1   0:20.32 flye                                                                              
 66194 kfuku     20   0   14.4g   1.9g     12 S   0.0  0.4  95:40.95 flye                                                                              
 66205 kfuku     20   0   14.4g   2.1g     12 S   0.0  0.4  97:10.28 flye                                                                              
 66211 kfuku     20   0   14.0g   1.1g     12 S   0.0  0.2  88:02.75 flye                                                                              
 66219 kfuku     20   0   13.8g 249296     52 S   0.0  0.0  91:50.59 flye                                                                              
 66226 kfuku     20   0   14.4g 196600     36 S   0.0  0.0  92:26.43 flye                                                                              
 66246 kfuku     20   0   14.1g   1.7g     12 S   0.0  0.3 101:43.05 flye                                                                              
 66260 kfuku     20   0   13.7g 435208     20 S   0.0  0.1  93:53.32 flye                                                                              
 66266 kfuku     20   0   14.5g 186180     12 S   0.0  0.0  93:37.33 flye                                                                              
 66272 kfuku     20   0   13.8g 547672     12 S   0.0  0.1  89:30.77 flye  
```

### tail of flye.log
```
-----------End assembly log------------
[2021-06-03 14:15:49] root: DEBUG: Disjointigs length: 4618736972, N50: 950866
[2021-06-03 14:15:50] root: INFO: >>>STAGE: consensus
[2021-06-03 14:16:42] root: INFO: Running Minimap2
[2021-06-04 16:53:31] root: INFO: Computing consensus
```

**Comment by ckeeling** [comment]
Hi @kfuku52 

Resuming the job doesn't help. The hang is reproducible. I would go straight to a different version of Python. The docker version of Flye I mentioned above worked well for me.

Cheers,

Chris

**Comment by bschiffthaler** [comment]
Some comments on the docker:

The docker container is built on `alpine:3.12` which ships `python3.8.7`. Source is [here](https://github.com/bschiffthaler/kogia/blob/master/flye/Dockerfile). If you want a higher version of Alpine and Python just change the `ARG` sections in the source and probably also drop L23-24. I'll move some containers to 3.13 in the coming days but I will need to the test assemblies again...

If you are going pure docker as opposed to Singularity keep in mind that docker doesn't by default run under an init system so zombies won't get reaped. Run with `docker run --init` to properly reap zombies.

**Comment by kfuku52** [comment]
Thank you both! I wanted to make sure if it's reproducible in my env, and confirmed the zombie with --resume. I'll start looking at the container soon.

**Comment by kfuku52** [comment]
flye successfully resumed running with the container. For those of you who run into the same error and need a work-around using a Singularity container:
```
singularity pull docker://bschiffthaler/flye
singularity exec flye_latest.sif flye --version
```

**Comment by ckeeling** [comment]
Good to hear @kfuku52 ! Thanks @bschiffthaler for making these Docker packages available.

**Comment by kfuku52** [comment]
Unfortunately, the run stuck at the same step even with the container built on `alpine:3.13`. I've started trying 3.12 by `singularity pull docker://bschiffthaler/flye:2.8.3`.

```
[2021-06-09 19:59:22] INFO: Starting Flye 2.8.3-b1695
[2021-06-09 19:59:23] INFO: Resuming previous run
[2021-06-09 19:59:24] INFO: >>>STAGE: consensus
[2021-06-09 20:01:18] INFO: Running Minimap2
[2021-06-11 07:33:15] INFO: Computing consensus
```

```
   PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                          
 95650 kfuku     20   0  174228   4356   1708 R   1.0  0.0   0:00.22 top                                                                                              
 71572 kfuku     20   0  126008     24     20 S   0.0  0.0   0:00.08 bash                                                                                             
 72319 kfuku     20   0  958588      0      0 S   0.0  0.0   0:00.38 starter-suid                                                                                     
 72345 kfuku     20   0 9315812 603816      8 S   0.0  0.1   4:18.62 python3                                                                                          
 94281 kfuku     20   0  177212   2428   1104 S   0.0  0.0   0:00.00 sshd                                                                                             
 94285 kfuku     20   0  127944   4368   1800 S   0.0  0.0   0:00.09 bash                                                                                             
111989 kfuku     20   0  248.7g 235.5g    200 S   0.0 46.8 148:47.13 python3                                                                                          
111997 kfuku     20   0       0      0      0 Z   0.0  0.0 109:16.01 python3                                                                                          
112001 kfuku     20   0   11.9g   1.1g    264 S   0.0  0.2   0:10.89 python3                                                                                          
112011 kfuku     20   0 9796.8m 626036     16 S   0.0  0.1 197:13.40 python3                                                                                          
112025 kfuku     20   0 9887.7m 632040     16 S   0.0  0.1 209:07.03 python3                                                                                          
112032 kfuku     20   0   10.5g 821544     16 S   0.0  0.2 210:41.97 python3                                                                                          
112043 kfuku     20   0   11.2g 846000     16 S   0.0  0.2 210:51.19 python3                                                                                          
112049 kfuku     20   0   10.5g 818356     16 S   0.0  0.2 212:38.91 python3                                                                                          
112055 kfuku     20   0 9973.5m 662380     16 S   0.0  0.1 217:36.87 python3                                                                                          
112061 kfuku     20   0   10.8g 893004     16 S   0.0  0.2 202:41.72 python3                                                                                          
112067 kfuku     20   0   10.6g 799508     16 S   0.0  0.2 204:09.36 python3                                                                                          
112073 kfuku     20   0 9848.5m 627532     16 S   0.0  0.1 205:59.62 python3                                                                                          
112079 kfuku     20   0   10.7g 916920     16 S   0.0  0.2 215:43.95 python3                                                                                          
112085 kfuku     20   0 9860.3m 661264     16 S   0.0  0.1 202:42.33 python3                                                                                          
112099 kfuku     20   0    9.9g 673024     16 S   0.0  0.1 207:10.18 python3                                                                                          
112105 kfuku     20   0   10.5g 800184     16 S   0.0  0.2 212:57.91 python3                                                                                          
112112 kfuku     20   0   10.5g 805852     16 S   0.0  0.2 208:10.58 python3                                                                                          
112118 kfuku     20   0   10.1g 685096     16 S   0.0  0.1 208:46.65 python3                                                                                          
112124 kfuku     20   0   10.5g 819456     16 S   0.0  0.2 212:05.04 python3                                                                                          
112130 kfuku     20   0 9833.6m 654116     16 S   0.0  0.1 215:54.23 python3                                                                                          
112136 kfuku     20   0   10.6g 835216     16 S   0.0  0.2 213:01.67 python3                                                                                          
112142 kfuku     20   0   10.8g 969072     16 S   0.0  0.2 212:42.47 python3 
```

**Comment by mikolmogorov** [comment]
@kfuku52 I suggest trying out a contained / package with a Python version other than 3.8.x

**Comment by kfuku52** [comment]
The container with `alpine:3.12` didn't work in my case, and I'm still in the same situation with a freshly created conda env with flye 2.83 + python 3.7.10.

I just realized that `10-consensus/chunks.fasta.fai` hasn't been replaced by `--resume` runs. I don't really think this is the cause of the problem, but just in case, I'm going to delete it and try again.

![image](https://user-images.githubusercontent.com/19270515/122535530-f4893e80-d023-11eb-872d-b076bec5bae3.png)

```
# packages in environment at /home/kfuku/.pyenv/versions/miniconda3-4.3.30/envs/flye:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
ca-certificates           2021.5.30            ha878542_0    conda-forge
certifi                   2021.5.30        py37h89c1867_0    conda-forge
flye                      2.8.3            py37hccf3b7b_1    bioconda
ld_impl_linux-64          2.35.1               hea4e1c9_2    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-ng                 9.3.0               h2828fa1_19    conda-forge
libgomp                   9.3.0               h2828fa1_19    conda-forge
libstdcxx-ng              9.3.0               h6de172a_19    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
openssl                   1.1.1k               h7f98852_0    conda-forge
pip                       21.1.2             pyhd8ed1ab_0    conda-forge
python                    3.7.10          hffdb5ce_100_cpython    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
setuptools                52.0.0           py37h06a4308_0  
sqlite                    3.35.5               h74cdb3f_0    conda-forge
tk                        8.6.10               hed695b0_1    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
```

```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                          
47995 kfuku     20   0  173392   3488   1640 R   0.3  0.0   0:00.09 top                                                                                                                              
18187 kfuku     20   0  125996      8      4 S   0.0  0.0   0:00.43 bash                                                                                                                             
19394 kfuku     20   0   13.1g 109692      4 S   0.0  0.0   2:57.00 flye                                                                                                                             
29051 kfuku     20   0  142.1g 124.8g      0 S   0.0 24.8 263:46.63 flye                                                                                                                             
29060 kfuku     20   0       0      0      0 Z   0.0  0.0 145:58.93 flye                                                                                                                             
29064 kfuku     20   0   18.1g 137832      0 S   0.0  0.0   0:19.38 flye                                                                                                                             
29080 kfuku     20   0   14.2g 338192      0 S   0.0  0.1 122:46.66 flye                                                                                                                             
29086 kfuku     20   0   13.8g   1.3g      0 S   0.0  0.3 126:09.51 flye                                                                                                                             
29093 kfuku     20   0   13.9g  99412      0 S   0.0  0.0 127:12.53 flye                                                                                                                             
29099 kfuku     20   0   14.1g   1.1g      0 S   0.0  0.2 110:27.18 flye                                                                                                                             
29105 kfuku     20   0   14.1g   1.4g      0 S   0.0  0.3 127:56.29 flye                                                                                                                             
29111 kfuku     20   0   13.8g 993.3m      0 S   0.0  0.2 111:49.14 flye                                                                                                                             
29117 kfuku     20   0   14.0g 130360      0 S   0.0  0.0 106:46.09 flye                                                                                                                             
29123 kfuku     20   0   14.1g   1.8g      0 S   0.0  0.4 127:26.53 flye                                                                                                                             
29129 kfuku     20   0   14.7g   1.8g      0 S   0.0  0.4 132:05.57 flye                                                                                                                             
29135 kfuku     20   0   13.8g   1.3g      0 S   0.0  0.2 104:17.26 flye                                                                                                                             
29141 kfuku     20   0   14.0g 167780      0 S   0.0  0.0 112:00.97 flye                                                                                                                             
29147 kfuku     20   0   14.3g 113240      0 S   0.0  0.0 129:36.87 flye                                                                                                                             
29154 kfuku     20   0   14.6g   1.9g      0 S   0.0  0.4 123:03.27 flye                                                                                                                             
29160 kfuku     20   0   13.6g 466848      0 S   0.0  0.1 119:52.49 flye                                                                                                                             
29166 kfuku     20   0   14.1g 882492      0 S   0.0  0.2 117:40.98 flye                                                                                                                             
29172 kfuku     20   0   14.3g   1.9g      0 S   0.0  0.4 116:48.39 flye                                                                                                                             
29178 kfuku     20   0   14.0g   1.0g      0 S   0.0  0.2 117:05.41 flye                                                                                                                             
29184 kfuku     20   0   14.1g 453172      0 S   0.0  0.1 125:15.04 flye                                                                                                                             
29190 kfuku     20   0   14.1g 759980      0 S   0.0  0.1 125:17.65 flye                                                                                                                             
29196 kfuku     20   0   14.5g   2.1g      0 S   0.0  0.4 118:55.00 flye                                                                                                                             
29202 kfuku     20   0   14.7g 112392      0 S   0.0  0.0 135:12.54 flye                                                                                                                             
29208 kfuku     20   0   13.4g 423308      0 S   0.0  0.1 117:38.51 flye                                                                                                                             
29215 kfuku     20   0   14.5g   1.7g      0 S   0.0  0.3 115:57.12 flye                                                                                                                             
29222 kfuku     20   0   14.1g   1.5g      0 S   0.0  0.3 131:08.32 flye                                                                                                                             
29228 kfuku     20   0   13.5g  95708      0 S   0.0  0.0 113:27.11 flye                                                                                                                             
29234 kfuku     20   0  114.0g  58.3g      0 S   0.0 11.6 127:23.69 flye                                                                                                                             
29240 kfuku     20   0   13.7g 197588      0 S   0.0  0.0 102:06.38 flye                                                                                                                             
29246 kfuku     20   0   14.1g 107112      0 S   0.0  0.0 120:10.79 flye                                                                                                                             
29252 kfuku     20   0   13.6g 102996      0 S   0.0  0.0 112:55.09 flye                                                                                                                             
29258 kfuku     20   0   14.0g   2.1g      0 S   0.0  0.4 114:21.64 flye                                                                                                                             
29264 kfuku     20   0   13.5g 486708      0 S   0.0  0.1 117:32.97 flye                                                                                                                             
29271 kfuku     20   0   14.5g 134624      0 S   0.0  0.0 102:22.81 flye                                                                                                                             
29277 kfuku     20   0   14.0g 675636      0 S   0.0  0.1 122:48.05 flye
```

**Comment by mikolmogorov** [comment]
@kfuku52 The `10-consensus/chunks.fasta.fai` should not be an issue. Does Flye hang on other datasets as well (e.g. the examples from the manual)? Could you give more information about your machine?

Also, I suggest trying to compile and run the latest github code. It reimplements some Python multiprocessing logic, so might potentially help with the hanging issue.

**Comment by kfuku52** [comment]
I've tried python 3.6, 3.7, and 3.8, with flye 2.8.3, but flye hangs at the same stage. The example E. coli dataset of Nanopore and PacBio reads were successfully assembled by flye 2.8.3 in combination with python 3.8.6 or 3.7.10 in the same environment, so the python version wouldn't be the root of this issue. I am assembling a 2-Gb plant genome from Nanopore data with `--asm-coverage 40`. The flye command is:
```
    flye \
    --out-dir ${prefix_outdir} \
    --threads ${NSLOTS} \
    --resume \
    --genome-size "${genome_size}g" \
    --asm-coverage ${subsampled_coverage} \
    --nano-raw "${files_nanopore_fasta[@]}"
```
I typically submit a job to UGE and use 64 CPUs on a machine that has 3TB RAM. We happen to have nearly 700Gb of input Nanopore reads. I guess the flye's consensus stage uses all data no matter what --asm-coverage is set. If so, is it possible that the problem comes from the too-large amount of input data?

**Comment by mikolmogorov** [comment]
@kfuku52 very likely, I would try manually downsampling the data to ~100x coverage and try again. Also, see my suggestion about running the latest source code above.

**Comment by kfuku52** [comment]
Hi @fenderglass I reduced the data amount to ca. x100 and resumed flye from the consensus stage with the command above. A zombie hasn't been spawned this time but flye doesn't seem to be using CPU efficiently. The top command is showing these results and this status has not changed for almost a week.

```
   PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                      
113705 kfuku     20   0   18.1g   1.0g    740 S  77.6  0.2   9807:52 flye                                                                                         
114043 kfuku     20   0   18.3g 746012    636 S   1.3  0.1 227:02.53 flye                                                                                         
 32229 kfuku     20   0  174056   4244   1712 R   1.0  0.0   0:00.07 top                                                                                          
113784 kfuku     20   0   14.3g   2.4g    688 S   1.0  0.5 226:38.43 flye                                                                                         
113801 kfuku     20   0   14.4g   2.5g    688 S   1.0  0.5 232:16.32 flye                                                                                         
113849 kfuku     20   0   14.4g   2.3g    688 S   1.0  0.5 211:34.57 flye                                                                                         
113903 kfuku     20   0   13.4g   1.1g    688 S   1.0  0.2 212:41.16 flye                                                                                         
113923 kfuku     20   0   14.4g   1.5g    688 S   1.0  0.3 218:58.17 flye                                                                                         
113957 kfuku     20   0   14.2g   1.6g    688 S   1.0  0.3 208:41.48 flye                                                                                         
113971 kfuku     20   0   14.3g   2.9g    688 S   1.0  0.6 219:01.83 flye                                                                                         
113980 kfuku     20   0   14.4g 985120    688 S   1.0  0.2 214:59.38 flye                                                                                         
114002 kfuku     20   0   13.9g   1.6g    688 S   1.0  0.3 209:51.45 flye                                                                                         
114056 kfuku     20   0   14.4g 654160    636 S   1.0  0.1 215:05.85 flye                                                                                         
114091 kfuku     20   0   14.5g   2.1g    688 S   1.0  0.4 231:31.85 flye                                                                                         
114125 kfuku     20   0   13.8g   1.3g    688 S   1.0  0.3 222:04.57 flye                                                                                         
114135 kfuku     20   0   13.9g   1.8g    688 S   1.0  0.4 218:00.53 flye                                                                                         
114142 kfuku     20   0   14.0g   2.4g    688 S   1.0  0.5 203:35.96 flye                                                                                         
114166 kfuku     20   0   14.0g   3.2g    688 S   1.0  0.6 207:50.78 flye                                                                                         
114181 kfuku     20   0   13.5g   1.2g    688 S   1.0  0.2 218:11.77 flye                                                                                         
114193 kfuku     20   0   14.4g   2.2g    688 S   1.0  0.4 214:17.88 flye                                                                                         
114199 kfuku     20   0   13.8g   1.2g    688 S   1.0  0.2 206:01.56 flye                                                                                         
114219 kfuku     20   0   14.4g 935872    688 S   1.0  0.2 219:59.22 flye                                                                                                                                                                               
```

I just realized there are many EOFError messages in flye.log. Similar problems are discussed in other Issues https://github.com/fenderglass/Flye/issues/40 https://github.com/fenderglass/Flye/issues/252 https://github.com/fenderglass/Flye/issues/300
```
[2021-06-25 21:07:00] root: ERROR: Traceback (most recent call last):
  File "/home/kfuku/.pyenv/versions/miniconda3-4.3.30/envs/flye/lib/python3.7/site-packages/flye/polishing/consensus.py", line 40, in _thread_worker
    ctg_id, ctg_aln = aln_reader.get_chunk()
  File "/home/kfuku/.pyenv/versions/miniconda3-4.3.30/envs/flye/lib/python3.7/site-packages/flye/utils/sam_parser.py", line 333, in get_chunk
    with self.shared_lock:
  File "/home/kfuku/.pyenv/versions/miniconda3-4.3.30/envs/flye/lib/python3.7/multiprocessing/managers.py", line 1053, in __enter__
    return self._callmethod('acquire')
  File "/home/kfuku/.pyenv/versions/miniconda3-4.3.30/envs/flye/lib/python3.7/multiprocessing/managers.py", line 819, in _callmethod
    kind, result = conn.recv()
  File "/home/kfuku/.pyenv/versions/miniconda3-4.3.30/envs/flye/lib/python3.7/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/home/kfuku/.pyenv/versions/miniconda3-4.3.30/envs/flye/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/kfuku/.pyenv/versions/miniconda3-4.3.30/envs/flye/lib/python3.7/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
```
It seems that I should downsample the input reads more, perhaps around x50.

**Comment by kfuku52** [comment]
I've successfully got the final assembly with x50 reads for consensus and later. Thank you!
