### ISSUE TITLE
Not compiling on aarch64

### ISSUE THREAD

**Issue by rungitta** [fenderglass/ABruijn#386]
I can't install this on a ARM-machine we have. Have this been done before? Do you have a fix for how to accomplish this?

```bash
$ python setup.py install --user
running install
running build
running build_py
make -C /home/pa/Flye/lib/minimap2 -j 4
make[1]: Entering directory '/home/pa/Flye/lib/minimap2'
cc -c -g -Wall -O2 -Wc++-compat  -msse2 -DHAVE_KALLOC  ksw2_ll_sse.c -o ksw2_ll_sse.o
cc -c -g -Wall -O2 -Wc++-compat  -msse4.1 -DHAVE_KALLOC -DKSW_CPU_DISPATCH  ksw2_extz2_sse.c -o ksw2_extz2_sse41.o
cc -c -g -Wall -O2 -Wc++-compat  -msse4.1 -DHAVE_KALLOC -DKSW_CPU_DISPATCH  ksw2_extd2_sse.c -o ksw2_extd2_sse41.o
cc -c -g -Wall -O2 -Wc++-compat  -msse4.1 -DHAVE_KALLOC -DKSW_CPU_DISPATCH  ksw2_exts2_sse.c -o ksw2_exts2_sse41.o
cc: error: unrecognized command line option ‘-msse2’
Makefile:51: recipe for target 'ksw2_ll_sse.o' failed
make[1]: *** [ksw2_ll_sse.o] Error 1
make[1]: *** Waiting for unfinished jobs....
cc: error: unrecognized command line option ‘-msse4.1’
cc: error: unrecognized command line option ‘-msse4.1’
Makefile:67: recipe for target 'ksw2_exts2_sse41.o' failed
make[1]: *** [ksw2_exts2_sse41.o] Error 1
Makefile:55: recipe for target 'ksw2_extz2_sse41.o' failed
make[1]: *** [ksw2_extz2_sse41.o] Error 1
cc: error: unrecognized command line option ‘-msse4.1’
Makefile:61: recipe for target 'ksw2_extd2_sse41.o' failed
make[1]: *** [ksw2_extd2_sse41.o] Error 1
make[1]: Leaving directory '/home/pa/Flye/lib/minimap2'
Makefile:20: recipe for target '/home/pa/Flye/bin/flye-minimap2' failed
make: *** [/home/pa/Flye/bin/flye-minimap2] Error 2
Traceback (most recent call last):
  File "setup.py", line 79, in <module>
    'install' : MakeInstall}
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 45, in run
    SetuptoolsInstall.run(self)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 65, in run
    orig.install.run(self)
  File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run
    self.run_command('build')
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 40, in run
    sys.exit("Compilation error: ", e)
TypeError: exit expected at most 1 arguments, got 2
```

**Comment by mikolmogorov** [comment]
Seems to be a minimap2 compilation issue. I don't have access to aarch64, so can't reproduce it on my side. Please refer to the compiling instructions at https://github.com/lh3/minimap2. It seems that modifying minimap2 compilation parameters (line 20 in Makefile) by adding `arm_neon=1 aarch64=1` should help.

**Comment by rungitta** [comment]
That in deed did help. Thank you :)

**Comment by mikolmogorov** [comment]
Glad that it helped. I'll refer to this thread in installation manual as a temporary solution.
