### ISSUE TITLE
Minimap2 nonexistent file 

### ISSUE THREAD

**Issue by vinibalvarenga** [fenderglass/ABruijn#409]
Hello, i was trying to install Flye on ubuntu 20.04 using the commands in the instructions, but i get those logs:

```
vinicius@vinicius-Inspiron-5547:~/Flye$ python setup.py install
running install
running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/flye
copying flye/six.py -> build/lib.linux-x86_64-2.7/flye
copying flye/__build__.py -> build/lib.linux-x86_64-2.7/flye
copying flye/main.py -> build/lib.linux-x86_64-2.7/flye
copying flye/__version__.py -> build/lib.linux-x86_64-2.7/flye
copying flye/__init__.py -> build/lib.linux-x86_64-2.7/flye
creating build/lib.linux-x86_64-2.7/flye/assembly
copying flye/assembly/assemble.py -> build/lib.linux-x86_64-2.7/flye/assembly
copying flye/assembly/repeat_graph.py -> build/lib.linux-x86_64-2.7/flye/assembly
copying flye/assembly/__init__.py -> build/lib.linux-x86_64-2.7/flye/assembly
copying flye/assembly/scaffolder.py -> build/lib.linux-x86_64-2.7/flye/assembly
creating build/lib.linux-x86_64-2.7/flye/config
copying flye/config/py_cfg.py -> build/lib.linux-x86_64-2.7/flye/config
copying flye/config/configurator.py -> build/lib.linux-x86_64-2.7/flye/config
copying flye/config/__init__.py -> build/lib.linux-x86_64-2.7/flye/config
creating build/lib.linux-x86_64-2.7/flye/polishing
copying flye/polishing/bubbles.py -> build/lib.linux-x86_64-2.7/flye/polishing
copying flye/polishing/polish.py -> build/lib.linux-x86_64-2.7/flye/polishing
copying flye/polishing/consensus.py -> build/lib.linux-x86_64-2.7/flye/polishing
copying flye/polishing/alignment.py -> build/lib.linux-x86_64-2.7/flye/polishing
copying flye/polishing/__init__.py -> build/lib.linux-x86_64-2.7/flye/polishing
creating build/lib.linux-x86_64-2.7/flye/utils
copying flye/utils/utils.py -> build/lib.linux-x86_64-2.7/flye/utils
copying flye/utils/fasta_parser.py -> build/lib.linux-x86_64-2.7/flye/utils
copying flye/utils/sam_parser.py -> build/lib.linux-x86_64-2.7/flye/utils
copying flye/utils/bytes2human.py -> build/lib.linux-x86_64-2.7/flye/utils
copying flye/utils/__init__.py -> build/lib.linux-x86_64-2.7/flye/utils
creating build/lib.linux-x86_64-2.7/flye/repeat_graph
copying flye/repeat_graph/repeat_graph.py -> build/lib.linux-x86_64-2.7/flye/repeat_graph
copying flye/repeat_graph/__init__.py -> build/lib.linux-x86_64-2.7/flye/repeat_graph
copying flye/repeat_graph/graph_alignment.py -> build/lib.linux-x86_64-2.7/flye/repeat_graph
creating build/lib.linux-x86_64-2.7/flye/short_plasmids
copying flye/short_plasmids/utils.py -> build/lib.linux-x86_64-2.7/flye/short_plasmids
copying flye/short_plasmids/circular_sequences.py -> build/lib.linux-x86_64-2.7/flye/short_plasmids
copying flye/short_plasmids/__init__.py -> build/lib.linux-x86_64-2.7/flye/short_plasmids
copying flye/short_plasmids/plasmids.py -> build/lib.linux-x86_64-2.7/flye/short_plasmids
copying flye/short_plasmids/unmapped_reads.py -> build/lib.linux-x86_64-2.7/flye/short_plasmids
creating build/lib.linux-x86_64-2.7/flye/trestle
copying flye/trestle/divergence.py -> build/lib.linux-x86_64-2.7/flye/trestle
copying flye/trestle/graph_resolver.py -> build/lib.linux-x86_64-2.7/flye/trestle
copying flye/trestle/trestle_config.py -> build/lib.linux-x86_64-2.7/flye/trestle
copying flye/trestle/trestle.py -> build/lib.linux-x86_64-2.7/flye/trestle
copying flye/trestle/__init__.py -> build/lib.linux-x86_64-2.7/flye/trestle
creating build/lib.linux-x86_64-2.7/flye/tests
copying flye/tests/test_toy.py -> build/lib.linux-x86_64-2.7/flye/tests
copying flye/tests/__init__.py -> build/lib.linux-x86_64-2.7/flye/tests
creating build/lib.linux-x86_64-2.7/flye/config/bin_cfg
copying flye/config/bin_cfg/pacbio_chm13_homopolymers.mat -> build/lib.linux-x86_64-2.7/flye/config/bin_cfg
copying flye/config/bin_cfg/nano_r94_g36_substitutions.mat -> build/lib.linux-x86_64-2.7/flye/config/bin_cfg
copying flye/config/bin_cfg/pacbio_chm13_substitutions.mat -> build/lib.linux-x86_64-2.7/flye/config/bin_cfg
copying flye/config/bin_cfg/asm_hifi.cfg -> build/lib.linux-x86_64-2.7/flye/config/bin_cfg
copying flye/config/bin_cfg/asm_subasm.cfg -> build/lib.linux-x86_64-2.7/flye/config/bin_cfg
copying flye/config/bin_cfg/pacbio_substitutions.mat -> build/lib.linux-x86_64-2.7/flye/config/bin_cfg
copying flye/config/bin_cfg/asm_raw_reads.cfg -> build/lib.linux-x86_64-2.7/flye/config/bin_cfg
copying flye/config/bin_cfg/nano_r94_homopolymers.mat -> build/lib.linux-x86_64-2.7/flye/config/bin_cfg
copying flye/config/bin_cfg/nano_r94_g36_homopolymers.mat -> build/lib.linux-x86_64-2.7/flye/config/bin_cfg
copying flye/config/bin_cfg/asm_defaults.cfg -> build/lib.linux-x86_64-2.7/flye/config/bin_cfg
copying flye/config/bin_cfg/nano_r94_substitutions.mat -> build/lib.linux-x86_64-2.7/flye/config/bin_cfg
copying flye/config/bin_cfg/asm_corrected_reads.cfg -> build/lib.linux-x86_64-2.7/flye/config/bin_cfg
copying flye/config/bin_cfg/pacbio_homopolymers.mat -> build/lib.linux-x86_64-2.7/flye/config/bin_cfg
creating build/lib.linux-x86_64-2.7/flye/tests/data
copying flye/tests/data/ecoli_500kb_reads.fastq.gz -> build/lib.linux-x86_64-2.7/flye/tests/data
copying flye/tests/data/ecoli_500kb.fasta -> build/lib.linux-x86_64-2.7/flye/tests/data
copying flye/tests/data/ecoli_500kb_reads_hifi.fastq.gz -> build/lib.linux-x86_64-2.7/flye/tests/data
make -C /home/vinicius/Flye/lib/minimap2 -j 4
make[1]: Entrando no diretório '/home/vinicius/Flye/lib/minimap2'
cc -c -g -Wall -O2 -Wc++-compat  -DHAVE_KALLOC  main.c -o main.o
cc -c -g -Wall -O2 -Wc++-compat  -DHAVE_KALLOC  kthread.c -o kthread.o
cc -c -g -Wall -O2 -Wc++-compat  -DHAVE_KALLOC  kalloc.c -o kalloc.o
cc -c -g -Wall -O2 -Wc++-compat  -DHAVE_KALLOC  misc.c -o misc.o
cc -c -g -Wall -O2 -Wc++-compat  -DHAVE_KALLOC  bseq.c -o bseq.o
bseq.c:1:10: fatal error: zlib.h: Arquivo ou diretório inexistente
    1 | #include <zlib.h>
      |          ^~~~~~~~
compilation terminated.
make[1]: *** [Makefile:39: bseq.o] Erro 1
make[1]: ** Esperando que outros processos terminem.
make[1]: Saindo do diretório '/home/vinicius/Flye/lib/minimap2'
make: *** [Makefile:20: /home/vinicius/Flye/bin/flye-minimap2] Erro 2
Traceback (most recent call last):
  File "setup.py", line 79, in <module>
    'install' : MakeInstall}
  File "/usr/lib/python2.7/dist-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 45, in run
    SetuptoolsInstall.run(self)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 65, in run
    orig.install.run(self)
  File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run
    self.run_command('build')
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 40, in run
    sys.exit("Compilation error: ", e)
TypeError: exit expected at most 1 arguments, got 2
```

some lines here are in Portuguese, my OS languague : 

fatal error: zlib.h: Arquivo ou diretório inexistente
it means: file or directory noexistent

make[1]: ** Esperando que outros processos terminem.
it means: Waiting for other processes to finish

make[1]: Saindo do diretório '/home/vinicius/Flye/lib/minimap2'
it means Leaving directory  '/home/vinicius/Flye/lib/minimap2'

i appreciate any help!

**Comment by mikolmogorov** [comment]
Please use the bioconda package instead, it does not require source compilation.
