### ISSUE TITLE
Error to read fasta in Flye 2.9-b1774

### ISSUE THREAD

**Issue by gushiro** [fenderglass/ABruijn#455]
I am using fasta as an input in my current Flye run, but got an error during the "configuration run".

```
[2021-12-03 07:26:12] INFO: Starting Flye 2.9-b1774
[2021-12-03 07:26:12] INFO: >>>STAGE: configure
[2021-12-03 07:26:12] INFO: Configuring run
Traceback (most recent call last):
  File "/home/user/usr/programs/Flye/bin/flye", line 25, in <module>
    sys.exit(main())
  File "/home/user/usr/programs/Flye/flye/main.py", line 830, in main
    _run(args)
  File "/home/user/usr/programs/Flye/flye/main.py", line 583, in _run
    jobs[i].run()
  File "/home/user/usr/programs/Flye/flye/main.py", line 95, in run
    params = setup_params(self.args)
  File "/home/user/usr/programs/Flye/flye/config/configurator.py", line 40, in setup_params
    for _, seq_len in iteritems(fp.read_sequence_lengths(read_file)):
  File "/home/user/usr/programs/Flye/flye/utils/fasta_parser.py", line 50, in read_sequence_lengths
    for hdr, seq in stream_sequence(filename):
  File "/home/user/usr/programs/Flye/flye/utils/fasta_parser.py", line 73, in stream_sequence
    for hdr, seq in _read_fasta(handle):
  File "/home/user/usr/programs/Flye/flye/utils/fasta_parser.py", line 146, in _read_fasta
    header = line[1:].split()[0]
IndexError: list index out of range
```

or maybe it is the format of the header in my fasta file?

**Comment by gushiro** [comment]
This was my error. The fasta was generated from masurca, and some sequences had errors (non-nucleotides or words related to the errors) due to the cluster shutdown we experienced.

**Comment by mikolmogorov** [comment]
Ok, glad it's resolved.
