### ISSUE TITLE
Opening assembly graph in gephi?

### ISSUE THREAD

**Issue by ewilbanks** [fenderglass/ABruijn#52]
Hi!

When I try to open the assembly_graph.dot with gephi, I get this error below.  It seems like gephi supports this file format, any ideas what might be going wrong here?  Suggestions for a different viewer?

Thanks!
Lizzy

java.lang.IllegalArgumentException: The id can't be empty
	at org.gephi.io.importer.impl.ImportContainerImpl.checkId(ImportContainerImpl.java:1045)
	at org.gephi.io.importer.impl.ImportContainerImpl.nodeExists(ImportContainerImpl.java:209)
	at org.gephi.io.importer.plugin.file.ImporterDOT.getOrCreateNode(ImporterDOT.java:197)
	at org.gephi.io.importer.plugin.file.ImporterDOT.stmt(ImporterDOT.java:181)
	at org.gephi.io.importer.plugin.file.ImporterDOT.stmtList(ImporterDOT.java:161)
	at org.gephi.io.importer.plugin.file.ImporterDOT.graph(ImporterDOT.java:149)
	at org.gephi.io.importer.plugin.file.ImporterDOT.importData(ImporterDOT.java:105)
	at org.gephi.io.importer.plugin.file.ImporterDOT.execute(ImporterDOT.java:87)
Caused: java.lang.RuntimeException
	at org.gephi.io.importer.plugin.file.ImporterDOT.execute(ImporterDOT.java:89)
	at org.gephi.io.importer.impl.ImportControllerImpl.importFile(ImportControllerImpl.java:199)
	at org.gephi.io.importer.impl.ImportControllerImpl.importFile(ImportControllerImpl.java:169)
	at org.gephi.desktop.importer.DesktopImportControllerUI$4.run(DesktopImportControllerUI.java:341)
Caused: java.lang.RuntimeException
	at org.gephi.desktop.importer.DesktopImportControllerUI$4.run(DesktopImportControllerUI.java:349)
[catch] at org.gephi.utils.longtask.api.LongTaskExecutor$RunningLongTask.run(LongTaskExecutor.java:274)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by mikolmogorov** [comment]
Hi,

We usually use Graphviz (https://www.graphviz.org/) for visualization:
    
    dot -Tpng -O graph.dot

I will take a look at Gephi and see if the problem is on our side. We are also now working on a custom interactive visualization - probably will include it into the next release. Finally, there is graph in .gfa format in the "2-repeat" folder, which could be visualized with Bandage.

**Comment by mikolmogorov** [comment]
Finally checked Gephi - it seems it does not fully support Graphviz language (custom edge attributes in particular). So Graphviz is the way to go for now.
