### ISSUE TITLE
Cannot install flye

### ISSUE THREAD

**Issue by leggylas** [fenderglass/ABruijn#560]
Hi, I use Mac OS Monterey with Mac M1 System. 

I have tried installing Flye with the conda installer and the source code, but there will still be an error while downloading the file, any idea how to solve it? 
 
Here is the error file: 
(base) kristintalia@Kristins-Air ~ % conda install flye
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - flye

Current channels:

  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

(base) kristintalia@Kristins-Air ~ % git clone https://github.com/fenderglass/Flye
cd Flye
python setup.py install
fatal: destination path 'Flye' already exists and is not an empty directory.
running install
/Users/kristintalia/opt/anaconda3/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running build
running build_py
make -C /Users/kristintalia/Flye/lib/minimap2 -j 4
cc -g -Wall -O2 -Wc++-compat  main.o -o minimap2 -L. -lminimap2 -lm -lz -lpthread
ld: warning: ignoring file main.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
Undefined symbols for architecture x86_64:
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [minimap2] Error 1
make: *** [/Users/kristintalia/Flye/bin/flye-minimap2] Error 2
Traceback (most recent call last):
  File "/Users/kristintalia/Flye/setup.py", line 38, in run
    subprocess.check_call(["make"])
  File "/Users/kristintalia/opt/anaconda3/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make']' returned non-zero exit status 2.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kristintalia/Flye/setup.py", line 69, in <module>
    setup(name='flye',
  File "/Users/kristintalia/opt/anaconda3/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/Users/kristintalia/opt/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/Users/kristintalia/opt/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/Users/kristintalia/opt/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 973, in run_commands
    self.run_command(cmd)
  File "/Users/kristintalia/opt/anaconda3/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/Users/kristintalia/opt/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
    cmd_obj.run()
  File "/Users/kristintalia/Flye/setup.py", line 45, in run
    SetuptoolsInstall.run(self)
  File "/Users/kristintalia/opt/anaconda3/lib/python3.9/site-packages/setuptools/command/install.py", line 72, in run
    orig.install.run(self)
  File "/Users/kristintalia/opt/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/command/install.py", line 692, in run
    self.run_command('build')
  File "/Users/kristintalia/opt/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
    self.distribution.run_command(command)
  File "/Users/kristintalia/opt/anaconda3/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/Users/kristintalia/opt/anaconda3/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
    cmd_obj.run()
  File "/Users/kristintalia/Flye/setup.py", line 40, in run
    sys.exit("Compilation error: ", e)
TypeError: exit expected at most 1 argument, got 2

**Comment by mikolmogorov** [comment]
You need to enable bioconda channel: https://bioconda.github.io/
