### ISSUE TITLE
Consistent TypeError Message

### ISSUE THREAD

**Issue by rmormando** [fenderglass/ABruijn#561]
Hello I keep getting this error message and I'm not sure what to do with it...

This is the command I've been running:

```
flye --nano-raw haplotype1.fq --out-dir flye_output --genome-size 12m --threads 20 --scaffold --keep-haplotypes
```

No matter if I run it with or without `---keep-haplotypes` it still gives this error message:

```
Traceback (most recent call last):
  File "/Users/rimo/opt/anaconda3/bin/flye", line 33, in <module>
    sys.exit(load_entry_point('flye==2.9', 'console_scripts', 'flye')())
  File "/Users/rimo/opt/anaconda3/lib/python3.9/site-packages/flye/main.py", line 846, in main
    _run(args)
  File "/Users/rimo/opt/anaconda3/lib/python3.9/site-packages/flye/main.py", line 586, in _run
    jobs[i].run()
  File "/Users/rimo/opt/anaconda3/lib/python3.9/site-packages/flye/main.py", line 364, in run
    pol.generate_polished_edges(self.in_graph_edges, self.in_graph_gfa,
  File "/Users/rimo/opt/anaconda3/lib/python3.9/site-packages/flye/polishing/polish.py", line 166, in generate_polished_edges
    for aln in aln_reader.get_all_alignments():
  File "/Users/rimo/opt/anaconda3/lib/python3.9/site-packages/flye/utils/sam_parser.py", line 476, in get_all_alignments
    aln = Alignment(_STR(read_id), _STR(parsed_contig),
TypeError: <lambda>() missing 1 required positional argument: 'haplotype'
```

I will note that the sample I am running it with is a phased-out yeast haplotype but I don't think that should influence the run at all as it's a de-novo assembly. My resulting folders get all the way to the polishing step before reaching this point. If anyone can help me understand what's happening and a possible solution that would be great!

**Comment by mikolmogorov** [comment]
It looks strange, are you using a binconda installation? The release version does not have a `haplotype` argument in this function. 

I recommend trying a clean installation in a new bioconda environemnt, make sure it's also the latest (`2.9.1`) and there are no other versions installed in your system.

**Comment by mikolmogorov** [comment]
Closed due to inactivity - feel free to reopen if you have any follow-ups.
