### ISSUE TITLE
Failing to get consensus

### ISSUE THREAD

**Issue by noncodo** [fenderglass/ABruijn#58]
Hi! 

When trying to assembly some nanopore data (including megabase long reads), I get the following: 

> [2018-09-11 08:40:17] INFO: Running Flye 2.3.6b-release
> [2018-09-11 08:40:17] INFO: Configuring run
> [2018-09-11 08:45:50] INFO: Input genome size: 2000000000
> [2018-09-11 08:45:50] INFO: Estimated coverage: 24
> [2018-09-11 08:45:50] INFO: Reads N50/N90: 21003 / 5366
> [2018-09-11 08:45:50] INFO: Selected k-mer size: 17
> [2018-09-11 08:45:50] INFO: Assembling reads
> [2018-09-11 08:45:50] INFO: Reading sequences
> [2018-09-11 09:47:47] INFO: Generating solid k-mer index
> [2018-09-11 09:58:19] INFO: Counting kmers (1/2):
> 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
> [2018-09-11 10:08:36] INFO: Counting kmers (2/2):
> 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
> [2018-09-11 10:41:35] INFO: Filling index table
> 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
> [2018-09-11 11:29:11] INFO: Extending reads
> [2018-09-11 11:40:31] INFO: Overlap-based coverage: 12
> [2018-09-11 11:40:31] INFO: Median overlap divergence: 0.0723281
> 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
> [2018-09-12 08:06:38] INFO: Assembled 19019 draft contigs
> [2018-09-12 08:07:12] INFO: Generating contig sequences
> 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
> [2018-09-12 09:50:27] INFO: Running Minimap2
> [2018-09-12 17:14:56] INFO: Computing consensus
> Traceback (most recent call last):
>   File "/home/marsmi/apps/Flye/bin/flye", line 31, in <module>
>     sys.exit(main())
>   File "/home/marsmi/apps/Flye/flye/main.py", line 517, in main
>     _run(args)
>   File "/home/marsmi/apps/Flye/flye/main.py", line 348, in _run
>     jobs[i].run()
>   File "/home/marsmi/apps/Flye/flye/main.py", line 197, in run
>     cfg.vals["min_aln_rate"])
>   File "/home/marsmi/apps/Flye/flye/polishing/consensus.py", line 80, in get_consensus
>     raise error_queue.get()
> AttributeError: __exit__

Any ideas?

**Comment by noncodo** [comment]
From the log file: 
> [2018-09-12 07:43:32] DEBUG: Inner: 5311838 covered: 6008664 total: 8228514
> [2018-09-12 07:43:35] DEBUG: Computing transitive closure for overlaps
> [2018-09-12 08:06:38] INFO: Assembled 19019 draft contigs
> [2018-09-12 08:07:12] INFO: Generating contig sequences
> [2018-09-12 09:47:48] DEBUG: Writing FASTA
> -----------End assembly log------------
> [2018-09-12 09:50:27] root: INFO: Running Minimap2
> [2018-09-12 09:50:27] root: DEBUG: Running: flye-minimap2  /share/ScratchGeneral/marsmi/778/flye/0-assembly/draft_assembly.fasta ./all_mapped_to_baits.fastq -a -Q -w5 -m100 -g10000 --max-chain-skip 25 -t 36 -k15
> [2018-09-12 17:03:59] root: DEBUG: Sorting alignment file
> [2018-09-12 17:14:56] root: INFO: Computing consensus

Some further digging after a sleep and a coffee reveals there might be something wrong with  the .sam output. Besides seemingly having no mapped reads, the output appears to be truncated.

> samtools view -F 4 minimap.sam | wc -l
>[W::sam_read1] Parse error at line 139271
> [main_samview] truncated file.

**Comment by mikolmogorov** [comment]
Hi,

Thanks for the extra information! Do your read headers happen to start with an '@' symbol?

**Comment by noncodo** [comment]
Think we found the problem: .sam file seems to have headers within it. 

> $ samtools view minimap.sam > /dev/null
> [W::sam_read1] Parse error at line 139271
> [main_samview] truncated file.

>$ head -n 139272  minimap.sam  |  tail -n 4 | cut -c 1-100
> ffff6010-994d-48d8-bd9a-d3f729494ad8	4	*	0	0	*	*	0	0	GTGTTGTACTTCGTTCATTTATGGATTAGTTACGTATTATACATTCA
> ffffd9da-b64d-4803-be01-b0c68b8d89c4	4	*	0	0	*	*	0	0	TCATTGTGCTTCGTTCGGTGCATTATTGCTATTCTGTTGAGTTCCAT
> @SQ	SN:contig_10094	LN:100000
> @SQ	SN:contig_4542	LN:100027

**Comment by mikolmogorov** [comment]
This is something expected - we use unix 'sort' to sort the SAM file, so the headers end up somewhere in the middle, which is ok for the parser that we use (in fact, in the latest version the headers should be in the top of the file).

Could you send me the full log and 'tail minimap.sam'? Also, could you run one of the small example datasets from USAGE.md to rule out the possible Python/libraries/installation issues?

**Comment by mikolmogorov** [comment]
Closing because of inactivity - please reopen if the problem remains.
