### ISSUE TITLE
polishing round 2

### ISSUE THREAD

**Issue by rwhetten** [fenderglass/ABruijn#594]
I'm encountering an error in the second iteration of polishing, using a recent installation of Flye from bioconda (build py310h590eda1_0), using a bam file of ONT reads error-corrected by FMLRC2 aligned to a draft assembly produced by wtdbg2. Command-line options are `--polish-target $DRAFT_ASSEMBLY --nano-hq $INPUT_BAM -t 36 -i 3 --scaffold `, and the log file contains multiple examples of two different error messages after the initial lines indicating that the first iteration completed successfully.
```
[2023-04-11 08:28:57] root: INFO: Polishing genome (1/3)
[2023-04-11 08:28:57] root: INFO: Polishing with provided bam
[2023-04-11 08:28:57] root: INFO: Separating alignment into bubbles
[2023-04-11 23:03:23] root: DEBUG: Generated 574951236 bubbles
[2023-04-11 23:03:23] root: DEBUG: Split 5969086 long bubbles
[2023-04-11 23:03:23] root: DEBUG: Skipped 7475733 empty bubbles
[2023-04-11 23:03:23] root: DEBUG: Skipped 8050 bubbles with long branches
[2023-04-11 23:03:32] root: INFO: Alignment error rate: 0.052056
[2023-04-11 23:03:32] root: INFO: Correcting bubbles
[2023-04-12 17:09:09] root: INFO: Polishing genome (2/3)
[2023-04-12 17:09:09] root: INFO: Polishing with provided bam
[2023-04-12 17:09:09] root: INFO: Separating alignment into bubbles
[2023-04-12 17:21:19] root: ERROR: Thread exception
[2023-04-12 17:21:19] root: ERROR: Traceback (most recent call last):
  File "bin/tools/flye_env/lib/python3.10/site-packages/flye/polishing/bubbles.py", line 76, in _thread_worker
    ctg_aln, mean_cov = get_uniform_alignments(ctg_aln)
  File "bin/tools/flye_env/lib/python3.10/site-packages/flye/polishing/alignment.py", line 113, in get_uniform_alignments
    wnd_primary_cov[i] += 1
IndexError: list index out of range
```
This error on lines 76 and 113 occurs nine times, and then a different error is reported:
```
[2023-04-12 17:23:29] root: ERROR: Thread exception
[2023-04-12 17:23:29] root: ERROR: Traceback (most recent call last):
  File "bin/tools/flye_env/lib/python3.10/site-packages/flye/polishing/bubbles.py", line 78, in _thread_worker
    profile, aln_errors = _compute_profile(ctg_aln, ref_seq)
  File "bin/tools/flye_env/lib/python3.10/site-packages/flye/polishing/bubbles.py", line 348, in _compute_profile
    trg_seq = shift_gaps(qry_seq, aln.trg_seq)
  File "bin/tools/flye_env/lib/python3.10/site-packages/flye/polishing/alignment.py", line 78, in shift_gaps
    if not is_gap and lst_qry[i] == "-":
IndexError: list index out of range
```
These two error messages continue to appear in combinations, one to four of one followed by one to four of the other, until a total of 40 error messages accumulate, and then the log file ends.

**Comment by rwhetten** [comment]
I have a subset of the assembly and BAM file (4 contigs, 671K file for the sequences and 9.5M for the alignments) that reproduces the problem. Visual inspection of the contig sequences suggests that the two contigs that cause problems (i.e. are not found in the partial polished_1.fasta output file) both contain more and longer homopolymer repeats and simple sequence repeats than one of the two that is processed successfully. I can provide the subset assembly and alignment files if that will be helpful.

**Comment by mikolmogorov** [comment]
Hi,

If you could send the example bam + reference that reproduces the error, this will be very helpful! You could send to fenderglass@gmail.com

Misha

**Comment by mikolmogorov** [comment]
Very sorry for my late reply! I was able to reproduce the issue - there is indeed an incompatibility between bam input and multiple polishing iterations. For multiple polishing iterations, you'd need to provide a fastq/fasta file with reads instead. I just added a check for that, so that the error message is more informative.
