### ISSUE TITLE
Exit Code:1 - RuntimeError

### ISSUE THREAD

**Issue by TimVMoser** [fenderglass/ABruijn#606]
Ahoy,
I am trying to de-Novo assemble ONT reads using Flye as a Geneious Prime plugin on a Mac (OS Ventura).
Reads were q20 trimmed and base-called using epi2me. The resulting fastq file was mapped to a reference genome and all reads mapping to a specific reference genome locus which contains gaps extracted for deNovo assembly. 
I now have a mere 5Mb across 1.3k reads which Iwould want to assemble to an expected consensus of ~70kb length.
It is entirely possible given error rates, the rather repetitive nature of the locus and my whole pipeline possibly being nonsense that this will not produce anything sensible. However, thus far all I get is Exit Code:1 - RuntimeError.

Below is the error report.
Any help is much appreciated. 
Thank You!
Tim

Error:  Failed to run: /Library/Application Support/Geneious/plugins/Flye/resources/MacOS/bin/flye --nano-corr input_0_Unpaired.fastq --threads 4 --genome-size 60000 --meta --iterations 2 --out-dir out, exit code: 1  
Flye reported the following errors: [2023-06-04 18:13:58] 
INFO: Starting Flye 2.7-b1585 [2023-06-04 18:13:58] 
INFO: >>>STAGE: configure [2023-06-04 18:13:58] 
INFO: Configuring run [2023-06-04 18:13:58] 
INFO: Total read length: 5009909 [2023-06-04 18:13:58] 
INFO: Input genome size: 60000 [2023-06-04 18:13:58] 
INFO: Estimated coverage: 83 [2023-06-04 18:13:58] 
INFO: Reads N50/N90: 7018 / 1361 [2023-06-04 18:13:58] 
INFO: Minimum overlap set to 1000 [2023-06-04 18:13:58] 
INFO: Selected k-mer size: 17 [2023-06-04 18:13:58] 
INFO: >>>STAGE: assembly [2023-06-04 18:13:58] 
INFO: Assembling disjointigs [2023-06-04 18:13:58] 
INFO: Reading sequences [2023-06-04 18:13:58] 
INFO: Generating solid k-mer index [2023-06-04 18:14:05] 
INFO: Counting k-mers (1/2): 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% [2023-06-04 18:14:05] 
INFO: Counting k-mers (2/2): 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% [2023-06-04 18:14:05] 
INFO: Filling index table (1/2) 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% [2023-06-04 18:14:06] 
INFO: Filling index table (2/2) 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% [2023-06-04 18:19:09] 
INFO: Extending reads [2023-06-04 18:29:58] 
INFO: Overlap-based coverage: 83 [2023-06-04 18:29:58] 
INFO: Median overlap divergence: 0.0777719 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% [2023-06-04 18:31:32] 
INFO: Assembled 2 disjointigs [2023-06-04 18:31:32] 
INFO: Generating sequence 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% [2023-06-04 18:31:33] 
INFO: >>>STAGE: consensus [2023-06-04 18:31:33] 
INFO: Running Minimap2 [2023-06-04 18:31:50] 
INFO: Computing consensus [2023-06-04 18:31:50] 
INFO: Starting Flye 2.7-b1585 [2023-06-04 18:31:50] 
INFO: >>>STAGE: configure [2023-06-04 18:31:50] 
INFO: Configuring run [2023-06-04 18:31:50] 
INFO: Total read length: 5009909 [2023-06-04 18:31:50] 
INFO: Input genome size: 60000 [2023-06-04 18:31:50] 
INFO: Estimated coverage: 83 [2023-06-04 18:31:50] 
INFO: Reads N50/N90: 7018 / 1361 [2023-06-04 18:31:50] 
INFO: Minimum overlap set to 1000 [2023-06-04 18:31:50] 
INFO: Selected k-mer size: 17 [2023-06-04 18:31:50] 
INFO: >>>STAGE: assembly [2023-06-04 18:31:50] 
INFO: Assembling disjointigs [2023-06-04 18:31:50] 
INFO: Reading sequences [2023-06-04 18:31:50] 
INFO: Generating solid k-mer index [2023-06-04 18:31:56] 
INFO: Counting k-mers (1/2): 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% [2023-06-04 18:31:56] 
INFO: Counting k-mers (2/2): 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% [2023-06-04 18:31:56] 
INFO: Filling index table (1/2) 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% [2023-06-04 18:31:57] 
INFO: Filling index table (2/2) 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% [2023-06-04 18:35:36] 
INFO: Extending reads [2023-06-04 18:45:44] 
INFO: Overlap-based coverage: 83 [2023-06-04 18:45:44] 
INFO: Median overlap divergence: 0.077516 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% [2023-06-04 18:47:17] 
INFO: Assembled 2 disjointigs [2023-06-04 18:47:17] 
INFO: Generating sequence 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% [2023-06-04 18:47:17] 
INFO: >>>STAGE: consensus [2023-06-04 18:47:17] 
INFO: Running Minimap2 [2023-06-04 18:47:33] 
INFO: Computing consensus Traceback (most recent call last): File " ", line 1, in   
File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main exitcode = _main(fd, parent_sentinel) 
File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 125, in _main prepare(preparation_data) 
File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare _fixup_main_from_path(data['init_main_from_path']) 
File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path main_content = runpy.run_path(main_path, 
File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 263, in run_path return _run_module_code(code, init_globals, run_name, 
File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 96, in _run_module_code _run_code(code, mod_globals, init_globals, 
File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/runpy.py", line 86, in _run_code exec(code, run_globals) 
File "/Library/Application Support/Geneious/plugins/Flye/resources/MacOS/bin/flye", line 25, in   sys.exit(main()) 
File "/Library/Application Support/Geneious/plugins/Flye/resources/MacOS/flye/main.py", line 779, in main _run(args) 
File "/Library/Application Support/Geneious/plugins/Flye/resources/MacOS/flye/main.py", line 568, in _run jobs[i].run() 
File "/Library/Application Support/Geneious/plugins/Flye/resources/MacOS/flye/main.py", line 323, in run consensus_fasta = cons.get_consensus(out_alignment, chunks_File, 
File "/Library/Application Support/Geneious/plugins/Flye/resources/MacOS/flye/polishing/consensus.py", line 57, in get_consensus aln_reader = SynchronizedSamReader(alignment_path, 
File "/Library/Application Support/Geneious/plugins/Flye/resources/MacOS/flye/utils/sam_parser.py", line 143, in __init__ self.shared_manager = multiprocessing.Manager() 
File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 57, in Manager m.start() 
File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/managers.py", line 579, in start self._process.start() 
File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 121, in start self._popen = self._Popen(self) 
File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 283, in _Popen return Popen(process_obj) 
File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__ super().__init__(process_obj) 
File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__ self._launch(process_obj) 
File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch prep_data = spawn.get_preparation_data(process_obj._name) 
File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data _check_not_importing_main() 
File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main raise RuntimeError(''' 

RuntimeError: An attempt has been made to start a new process before the current process has finished its bootstrapping phase.  This probably means that you are not using fork to start your child processes and you have forgotten to use the proper idiom in the main module:  if __name__ == '__main__': freeze_support() ...  The "freeze_support()" line can be omitted if the program is not going to be frozen to produce an executable. 
Traceback (most recent call last): 
File "/Library/Application Support/Geneious/plugins/Flye/resources/MacOS/bin/flye", line 25, in   sys.exit(main()) 
File "/Library/Application Support/Geneious/plugins/Flye/resources/MacOS/flye/main.py", line 779, in main _run(args) 
File "/Library/Application Support/Geneious/plugins/Flye/resources/MacOS/flye/main.py", line 568, in _run jobs[i].run() 
File "/Library/Application Support/Geneious/plugins/Flye/resources/MacOS/flye/main.py", line 323, in run consensus_fasta = cons.get_consensus(out_alignment, chunks_File, 
File "/Library/Application Support/Geneious/plugins/Flye/resources/MacOS/flye/polishing/consensus.py", line 57, in get_consensus aln_reader = SynchronizedSamReader(alignment_path, 
File "/Library/Application Support/Geneious/plugins/Flye/resources/MacOS/flye/utils/sam_parser.py", line 143, in __init__ self.shared_manager = multiprocessing.Manager() 
File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 57, in Manager m.start() 
File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/managers.py", line 583, in start self._address = reader.recv() 
File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/connection.py", line 250, in recv buf = self._recv_bytes() 
File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes buf = self._recv(4) 
File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/multiprocessing/connection.py", line 383, in _recv raise EOFError EOFError

com.biomatters.geneious.publicapi.plugin.DocumentOperationException at 
com.biomatters.iseek.plugin.wrapperplugins.WrapperOperation.a(WrapperOperation.java:518) at 
com.biomatters.iseek.plugin.wrapperplugins.WrapperOperation.a(WrapperOperation.java:220) at 
com.biomatters.iseek.plugin.wrapperplugins.WrapperAssembler.assemble(WrapperAssembler.java:91) at 
com.biomatters.plugins.alignment.assembly.AssemblyOperation.performOperation(AssemblyOperation.java:850) at 
com.biomatters.iseek.plugin.operations.o.b(OperationManager.java:513) at 
com.biomatters.geneious.common.operations.c.c(OperationsUtilities.java:165) at 
com.biomatters.geneious.common.operations.c.b(OperationsUtilities.java:162) at 
com.biomatters.geneious.common.operations.b$c.a(OperationsUtilities.java:141) at 
com.biomatters.geneious.common.operations.b$d.a(OperationsUtilities.java:168) at 
com.biomatters.iseek.plugin.operations.e.a(OperationManager.java:518) at 
com.biomatters.iseek.plugin.operations.s.a(OperationPerformer.java:136) at 
com.biomatters.iseek.plugin.operations.OperationAction.performAction(OperationAction.java:116) at 
com.biomatters.iseek.plugin.operations.a.run(OperationAction.java:92) at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by mikolmogorov** [comment]
You are using an old Flye version, update to the most recent release should fix this. I do not maintain Geneious platform, any issues specific to this platform should be reported to its developers.

**Comment by TimVMoser** [comment]
Thank You!!!
