### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '[]\n'

### ISSUE THREAD

**Issue by alexvasilikop** [fenderglass/ABruijn#630]
Hello,

 I am using Flye v. 2.9.2-b1786 within a conda environment.

The following error pops up at the end of the pipeline:
```
outdir=/mnt/sda1/Alex/16.PHASED_ASSEMBLIES_HETEROZYGOSITY/Adineta_ricciae/01.FLYE/Flye_aricciae_ONT                
reads=/mnt/sda1/Alex/16.PHASED_ASSEMBLIES_HETEROZYGOSITY/Adineta_ricciae/Adineta_ricciae.ONT.BXQ_G.merged.filt.40000.90.1000.fastq
threads=12

flye --nano-raw $reads --threads $threads --out-dir $outdir
[2023-08-14 10:38:32] INFO: Starting Flye 2.9.2-b1786
[2023-08-14 10:38:32] INFO: >>>STAGE: configure
[2023-08-14 10:38:32] INFO: Configuring run
[2023-08-14 10:40:17] INFO: Total read length: 4713029744
[2023-08-14 10:40:17] INFO: Reads N50/N90: 58040 / 43078
[2023-08-14 10:40:17] INFO: Minimum overlap set to 10000
[2023-08-14 10:40:17] INFO: >>>STAGE: assembly
[2023-08-14 10:40:17] INFO: Assembling disjointigs
[2023-08-14 10:40:17] INFO: Reading sequences
[2023-08-14 10:40:45] INFO: Counting k-mers:
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 
[2023-08-14 10:47:32] INFO: Filling index table (1/2)
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 
[2023-08-14 10:55:12] INFO: Filling index table (2/2)
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 
[2023-08-14 11:01:56] INFO: Extending reads
[2023-08-14 11:07:29] INFO: Overlap-based coverage: 22
[2023-08-14 11:07:29] INFO: Median overlap divergence: 0.13008
0% 20% 30% 40% 50% 70% 80% 90% 100% 
[2023-08-14 11:41:19] INFO: Assembled 386 disjointigs
[2023-08-14 11:41:26] INFO: Generating sequence
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 
[2023-08-14 11:43:21] INFO: Filtering contained disjointigs
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 
[2023-08-14 11:43:54] INFO: Contained seqs: 8
[2023-08-14 11:44:03] INFO: >>>STAGE: consensus
[2023-08-14 11:44:03] INFO: Running Minimap2
[2023-08-14 12:03:21] INFO: Computing consensus
[2023-08-14 12:16:29] INFO: Alignment error rate: 0.210915
[2023-08-14 12:16:31] INFO: >>>STAGE: repeat
[2023-08-14 12:16:31] INFO: Building and resolving repeat graph
[2023-08-14 12:16:31] INFO: Parsing disjointigs
[2023-08-14 12:16:33] INFO: Building repeat graph
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 
[2023-08-14 12:24:57] INFO: Median overlap divergence: 0.107706
[2023-08-14 12:25:02] INFO: Parsing reads
[2023-08-14 12:25:23] INFO: Aligning reads to the graph
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 
[2023-08-14 12:33:39] INFO: Aligned read sequence: 4184498993 / 4713029744 (0.887858)
[2023-08-14 12:33:39] INFO: Median overlap divergence: 0.0763576
[2023-08-14 12:33:40] INFO: Mean edge coverage: 29
[2023-08-14 12:33:40] INFO: Simplifying the graph
[2023-08-14 12:33:51] INFO: >>>STAGE: contigger
[2023-08-14 12:33:51] INFO: Generating contigs
[2023-08-14 12:33:51] INFO: Reading sequences
[2023-08-14 12:34:18] INFO: Generated 1437 contigs
[2023-08-14 12:34:20] INFO: Added 5 scaffold connections
[2023-08-14 12:34:25] INFO: >>>STAGE: polishing
[2023-08-14 12:34:25] INFO: Polishing genome (1/1)
[2023-08-14 12:34:25] INFO: Running minimap2
[2023-08-14 12:48:46] INFO: Separating alignment into bubbles
[2023-08-14 13:02:17] INFO: Alignment error rate: 0.177643
[2023-08-14 13:02:17] INFO: Correcting bubbles
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100% 
Traceback (most recent call last):
  File "/home/lege/anaconda3/envs/flye_2.9.2/bin/flye", line 33, in <module>
    sys.exit(load_entry_point('flye==2.9.2', 'console_scripts', 'flye')())
  File "/home/lege/anaconda3/envs/flye_2.9.2/lib/python3.10/site-packages/flye/main.py", line 751, in main
    _run(args)
  File "/home/lege/anaconda3/envs/flye_2.9.2/lib/python3.10/site-packages/flye/main.py", line 490, in _run
    jobs[i].run()
  File "/home/lege/anaconda3/envs/flye_2.9.2/lib/python3.10/site-packages/flye/main.py", line 324, in run
    pol.filter_by_coverage(self.args, stats, contigs,
  File "/home/lege/anaconda3/envs/flye_2.9.2/lib/python3.10/site-packages/flye/polishing/polish.py", line 242, in filter_by_coverage
    ctg_id, ctg_len, ctg_cov = tokens[0], int(tokens[1]), int(tokens[2])
ValueError: invalid literal for int() with base 10: '[]\n'
```

Any idea what the problem is?
Thanks
Alex

**Comment by mikolmogorov** [comment]
Please see #620
