### ISSUE TITLE
OSError: AF_UNIX path too long

### ISSUE THREAD

**Issue by jolespin** [fenderglass/ABruijn#653]
Here's my command: 

```
flye --nano-hq veba_output/preprocess/SRR8641380/output/cleaned.fastq.gz -g 1m -o veba_output/assembly/SRR8641380/intermediate/1__assembly -t 4 --deterministic
```

Here's my version: 

```
(VEBA-assembly_env) [jespinoz@exp-15-34 Pneumocystis]$ flye -v
2.9.3-b1797
```

Here's the stderr: 

```
(VEBA-assembly_env) [jespinoz@exp-15-34 Pneumocystis]$ cat veba_output/assembly/SRR8641380/log/1__assembly.e
[2023-11-30 15:46:42] INFO: Starting Flye 2.9.3-b1797
[2023-11-30 15:46:42] INFO: >>>STAGE: configure
[2023-11-30 15:46:42] INFO: Configuring run
[2023-11-30 15:46:44] INFO: Total read length: 95801872
[2023-11-30 15:46:44] INFO: Input genome size: 1000000
[2023-11-30 15:46:44] INFO: Estimated coverage: 95
[2023-11-30 15:46:44] INFO: Reads N50/N90: 872 / 564
[2023-11-30 15:46:44] INFO: Minimum overlap set to 1000
[2023-11-30 15:46:44] INFO: >>>STAGE: assembly
[2023-11-30 15:46:44] INFO: Assembling disjointigs
[2023-11-30 15:46:44] INFO: Reading sequences
[2023-11-30 15:46:46] INFO: Building minimizer index
[2023-11-30 15:46:46] INFO: Pre-calculating index storage
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
[2023-11-30 15:46:49] INFO: Filling index
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
[2023-11-30 15:46:52] INFO: Extending reads
[2023-11-30 15:46:53] INFO: Overlap-based coverage: 1
[2023-11-30 15:46:53] INFO: Median overlap divergence: 0.18
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
[2023-11-30 15:47:06] INFO: Assembled 39 disjointigs
[2023-11-30 15:47:07] INFO: Generating sequence
0% 10% 20% 40% 50% 70% 80% 100%
[2023-11-30 15:47:07] INFO: Filtering contained disjointigs
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
[2023-11-30 15:47:07] INFO: Contained seqs: 4
[2023-11-30 15:47:07] INFO: >>>STAGE: consensus
[2023-11-30 15:47:07] INFO: Running Minimap2
[2023-11-30 15:47:33] INFO: Computing consensus
Process SyncManager-1:
Traceback (most recent call last):
  File "/expanse/projects/jcl110/anaconda3/envs/VEBA-assembly_env/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/expanse/projects/jcl110/anaconda3/envs/VEBA-assembly_env/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/expanse/projects/jcl110/anaconda3/envs/VEBA-assembly_env/lib/python3.9/multiprocessing/managers.py", line 583, in _run_server
    server = cls._Server(registry, address, authkey, serializer)
  File "/expanse/projects/jcl110/anaconda3/envs/VEBA-assembly_env/lib/python3.9/multiprocessing/managers.py", line 156, in __init__
    self.listener = Listener(address=address, backlog=16)
  File "/expanse/projects/jcl110/anaconda3/envs/VEBA-assembly_env/lib/python3.9/multiprocessing/connection.py", line 448, in __init__
    self._listener = SocketListener(address, family, backlog)
  File "/expanse/projects/jcl110/anaconda3/envs/VEBA-assembly_env/lib/python3.9/multiprocessing/connection.py", line 591, in __init__
    self._socket.bind(address)
OSError: AF_UNIX path too long
Traceback (most recent call last):
  File "/expanse/projects/jcl110/anaconda3/envs/VEBA-assembly_env/bin/flye", line 33, in <module>
    sys.exit(load_entry_point('flye==2.9.3', 'console_scripts', 'flye')())
  File "/expanse/projects/jcl110/anaconda3/envs/VEBA-assembly_env/lib/python3.9/site-packages/flye/main.py", line 756, in main
    _run(args)
  File "/expanse/projects/jcl110/anaconda3/envs/VEBA-assembly_env/lib/python3.9/site-packages/flye/main.py", line 493, in _run
    jobs[i].run()
  File "/expanse/projects/jcl110/anaconda3/envs/VEBA-assembly_env/lib/python3.9/site-packages/flye/main.py", line 284, in run
    consensus_fasta = cons.get_consensus(out_alignment, self.in_contigs,
  File "/expanse/projects/jcl110/anaconda3/envs/VEBA-assembly_env/lib/python3.9/site-packages/flye/polishing/consensus.py", line 71, in get_consensus
    mp_manager = multiprocessing.Manager()
  File "/expanse/projects/jcl110/anaconda3/envs/VEBA-assembly_env/lib/python3.9/multiprocessing/context.py", line 57, in Manager
    m.start()
  File "/expanse/projects/jcl110/anaconda3/envs/VEBA-assembly_env/lib/python3.9/multiprocessing/managers.py", line 558, in start
    self._address = reader.recv()
  File "/expanse/projects/jcl110/anaconda3/envs/VEBA-assembly_env/lib/python3.9/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/expanse/projects/jcl110/anaconda3/envs/VEBA-assembly_env/lib/python3.9/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/expanse/projects/jcl110/anaconda3/envs/VEBA-assembly_env/lib/python3.9/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
```

Here's the returncode: 

```
(VEBA-assembly_env) [jespinoz@exp-15-34 Pneumocystis]$ cat veba_output/assembly/SRR8641380/log/1__assembly.returncode
1
```

Reads I used are here: 
https://drive.google.com/file/d/1c_agU2Pl6AA6BoMaZUXtU5Q1XCH6F45W/view?usp=sharing

They are ~90MB in size. 

I also tried 1 thread too.

**Comment by mikolmogorov** [comment]
Do example dataset provided in the manual work for you? based on the error log, it has something to do with the Python multiprocessing library, and is likely connected to the Python environment. Python may create files corresponding to network sockets for multiprocessing. I would try to check if other Python packages that use multiprocessing are giving you the same error.

**Comment by jolespin** [comment]
This is definitely the case.  I'll need to figure out how to get around this in Python.  I've used a smaller filepath for tmp directory and it works great.
