### ISSUE TITLE
installation error flye.six.moves

### ISSUE THREAD

**Issue by anke-king** [fenderglass/ABruijn#714]
I tried installing flye and got the following error:

Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/bin/flye", line 33, in <module>
    sys.exit(load_entry_point('flye==2.9.4', 'console_scripts', 'flye')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/bin/flye", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/lib/python3.12/importlib/metadata/__init__.py", line 205, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ubuntu/miniconda3/lib/python3.12/site-packages/flye/main.py", line 19, in <module>
    import flye.polishing.alignment as aln
  File "/home/ubuntu/miniconda3/lib/python3.12/site-packages/flye/polishing/alignment.py", line 18, in <module>
    import flye.utils.fasta_parser as fp
  File "/home/ubuntu/miniconda3/lib/python3.12/site-packages/flye/utils/fasta_parser.py", line 26, in <module>
    from flye.six.moves import range
ModuleNotFoundError: No module named 'flye.six.moves'

**Comment by mikolmogorov** [comment]
Python 3.12 is currently not supported. https://github.com/mikolmogorov/Flye/issues/669
