### ISSUE TITLE
OSError: AF_UNIX path too long

### ISSUE THREAD

**Issue by buchanri** [fenderglass/ABruijn#727]
Hello, I'm running flye on a nanopore SRA from the NCBI. Here's my command
```flye --nano-hq SRR24768107.fastq.gz --out-dir . --threads 8 ```
 
I'm using 
`INFO: Starting Flye 2.9.5-b1801`

However I get this error

```[2024-09-19 12:24:11] INFO: Contained seqs: 0
  [2024-09-19 12:24:13] INFO: >>>STAGE: consensus
  [2024-09-19 12:24:13] INFO: Running Minimap2
  [2024-09-19 12:31:40] INFO: Computing consensus
  Process SyncManager-1:
  Traceback (most recent call last):
    File "/nfs7/BPP/Chang_Lab/paradarc/paper1_bra/scripts/ps_pipeline_riley/pathogensurveillance/work/conda/flye-70b1e8013f58726c7d7de72305dde91d/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
      self.run()
    File "/nfs7/BPP/Chang_Lab/paradarc/paper1_bra/scripts/ps_pipeline_riley/pathogensurveillance/work/conda/flye-70b1e8013f58726c7d7de72305dde91d/lib/python3.12/multiprocessing/process.py", line 108, in run
      self._target(*self._args, **self._kwargs)
    File "/nfs7/BPP/Chang_Lab/paradarc/paper1_bra/scripts/ps_pipeline_riley/pathogensurveillance/work/conda/flye-70b1e8013f58726c7d7de72305dde91d/lib/python3.12/multiprocessing/managers.py", line 591, in _run_server
      server = cls._Server(registry, address, authkey, serializer)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/nfs7/BPP/Chang_Lab/paradarc/paper1_bra/scripts/ps_pipeline_riley/pathogensurveillance/work/conda/flye-70b1e8013f58726c7d7de72305dde91d/lib/python3.12/multiprocessing/managers.py", line 156, in __init__
      self.listener = Listener(address=address, backlog=128)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/nfs7/BPP/Chang_Lab/paradarc/paper1_bra/scripts/ps_pipeline_riley/pathogensurveillance/work/conda/flye-70b1e8013f58726c7d7de72305dde91d/lib/python3.12/multiprocessing/connection.py", line 464, in __init__
      self._listener = SocketListener(address, family, backlog)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/nfs7/BPP/Chang_Lab/paradarc/paper1_bra/scripts/ps_pipeline_riley/pathogensurveillance/work/conda/flye-70b1e8013f58726c7d7de72305dde91d/lib/python3.12/multiprocessing/connection.py", line 608, in __init__
      self._socket.bind(address)
  OSError: AF_UNIX path too long
  Traceback (most recent call last):
    File "/nfs7/BPP/Chang_Lab/paradarc/paper1_bra/scripts/ps_pipeline_riley/pathogensurveillance/work/conda/flye-70b1e8013f58726c7d7de72305dde91d/bin/flye", line 11, in <module>
      sys.exit(main())
               ^^^^^^
    File "/nfs7/BPP/Chang_Lab/paradarc/paper1_bra/scripts/ps_pipeline_riley/pathogensurveillance/work/conda/flye-70b1e8013f58726c7d7de72305dde91d/lib/python3.12/site-packages/flye/main.py", line 761, in main
      _run(args)
    File "/nfs7/BPP/Chang_Lab/paradarc/paper1_bra/scripts/ps_pipeline_riley/pathogensurveillance/work/conda/flye-70b1e8013f58726c7d7de72305dde91d/lib/python3.12/site-packages/flye/main.py", line 498, in _run
      jobs[i].run()
    File "/nfs7/BPP/Chang_Lab/paradarc/paper1_bra/scripts/ps_pipeline_riley/pathogensurveillance/work/conda/flye-70b1e8013f58726c7d7de72305dde91d/lib/python3.12/site-packages/flye/main.py", line 287, in run
      consensus_fasta = cons.get_consensus(out_alignment, self.in_contigs,
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/nfs7/BPP/Chang_Lab/paradarc/paper1_bra/scripts/ps_pipeline_riley/pathogensurveillance/work/conda/flye-70b1e8013f58726c7d7de72305dde91d/lib/python3.12/site-packages/flye/polishing/consensus.py", line 71, in get_consensus
      mp_manager = multiprocessing.Manager()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/nfs7/BPP/Chang_Lab/paradarc/paper1_bra/scripts/ps_pipeline_riley/pathogensurveillance/work/conda/flye-70b1e8013f58726c7d7de72305dde91d/lib/python3.12/multiprocessing/context.py", line 57, in Manager
      m.start()
    File "/nfs7/BPP/Chang_Lab/paradarc/paper1_bra/scripts/ps_pipeline_riley/pathogensurveillance/work/conda/flye-70b1e8013f58726c7d7de72305dde91d/lib/python3.12/multiprocessing/managers.py", line 566, in start
      self._address = reader.recv()
                      ^^^^^^^^^^^^^
    File "/nfs7/BPP/Chang_Lab/paradarc/paper1_bra/scripts/ps_pipeline_riley/pathogensurveillance/work/conda/flye-70b1e8013f58726c7d7de72305dde91d/lib/python3.12/multiprocessing/connection.py", line 250, in recv
      buf = self._recv_bytes()
            ^^^^^^^^^^^^^^^^^^
    File "/nfs7/BPP/Chang_Lab/paradarc/paper1_bra/scripts/ps_pipeline_riley/pathogensurveillance/work/conda/flye-70b1e8013f58726c7d7de72305dde91d/lib/python3.12/multiprocessing/connection.py", line 430, in _recv_bytes
      buf = self._recv(4)
            ^^^^^^^^^^^^^
    File "/nfs7/BPP/Chang_Lab/paradarc/paper1_bra/scripts/ps_pipeline_riley/pathogensurveillance/work/conda/flye-70b1e8013f58726c7d7de72305dde91d/lib/python3.12/multiprocessing/connection.py", line 399, in _recv
      raise EOFError
  EOFError
```

Any thoughts on how to fix? I'm also running on a cluster, not on my local computer. I also tried setting the tmp directory to where I am running at so that the path is short, but it did not work.

**Comment by mikolmogorov** [comment]
It's complaining at the path where flye is installed - try to put the conda environment to a shorter path. It's an issue with certain Python versions.

**Comment by buchanri** [comment]
I'm running it through Nextflow and it creates weirdly long directories. What python version would you suggest? I'm using Python 3.12.6

**Comment by mikolmogorov** [comment]
I think it may have something to do with specific Python implementations, not versions, can give you a specific solution unfortunately. I'd try shortening the working directory path as much as you can and check if that helps.

**Comment by Kevin-Brockers** [comment]
I ran into the same problem.

Fixed it using and older python version, please find the conda env below.

I cannot change the conda env path due to some restrictions on the hpc I'm using.

```
channels:
  - bioconda
  - conda-forge
dependencies:
  - python =3.9.5
  - flye =2.9.5
```
