### ISSUE TITLE
Computing consensus fails

### ISSUE THREAD

**Issue by robinjugas** [fenderglass/ABruijn#86]
Hi, I appreciate this work. 
However, I tried running flye twice with the same arguments (its bioconda version 2.4.1). Those are nanopore reads. But it always failed on this. What could be the issue?
Thank you. 

flye --nano-raw reads.fastq --out-dir out_nano2 --genome-size 30m --threads 4
[2019-03-13 11:57:10] INFO: Starting Flye 2.4.1-release
[2019-03-13 11:57:10] INFO: >>>STAGE: configure
[2019-03-13 11:57:10] INFO: Configuring run
[2019-03-13 11:57:33] INFO: Input genome size: 30000000
[2019-03-13 11:57:33] INFO: Estimated coverage: 50
[2019-03-13 11:57:33] INFO: Reads N50/N90: 32857 / 6719
[2019-03-13 11:57:33] INFO: Minimum overlap set to 5000
[2019-03-13 11:57:33] INFO: Selected k-mer size: 15
[2019-03-13 11:57:33] INFO: >>>STAGE: assembly
[2019-03-13 11:57:33] INFO: Assembling reads
[2019-03-13 11:57:33] INFO: Reading sequences
[2019-03-13 11:57:40] INFO: Generating solid k-mer index
[2019-03-13 11:57:58] INFO: Counting kmers (1/2):
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
[2019-03-13 11:58:55] INFO: Counting kmers (2/2):
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
[2019-03-13 12:01:28] INFO: Filling index table
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
[2019-03-13 12:04:00] INFO: Extending reads
[2019-03-13 12:14:42] INFO: Overlap-based coverage: 43
[2019-03-13 12:14:42] INFO: Median overlap divergence: 0.110745
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
[2019-03-13 14:58:29] INFO: Assembled 239 draft contigs
[2019-03-13 14:58:30] INFO: Generating contig sequences
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
[2019-03-13 15:10:58] INFO: >>>STAGE: consensus
[2019-03-13 15:10:58] INFO: Running Minimap2
[2019-03-13 15:21:53] INFO: Computing consensus
Traceback (most recent call last):
  File "/home/rj/miniconda3/bin/flye", line 31, in <module>
    sys.exit(main())
  File "/home/rj/miniconda3/lib/python2.7/site-packages/flye/main.py", line 719, in main
    _run(args)
  File "/home/rj/miniconda3/lib/python2.7/site-packages/flye/main.py", line 529, in _run
    jobs[i].run()
  File "/home/rj/miniconda3/lib/python2.7/site-packages/flye/main.py", line 300, in run
    self.args.platform)
  File "/home/rj/miniconda3/lib/python2.7/site-packages/flye/polishing/consensus.py", line 79, in get_consensus
    .format(t.exitcode))
Exception: One of the processes exited with code: -11
Process Process-4:
Traceback (most recent call last):
  File "/home/rj/miniconda3/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/home/rj/miniconda3/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rj/miniconda3/lib/python2.7/site-packages/flye/polishing/consensus.py", line 45, in _thread_worker
    error_queue.put(e)
  File "<string>", line 2, in put
  File "/home/rj/miniconda3/lib/python2.7/multiprocessing/managers.py", line 758, in _callmethod
    conn.send((self._id, methodname, args, kwds))
IOError: [Errno 32] Broken pipe

**Comment by mikolmogorov** [comment]
Hi, 

Can you post the flye.log file? How much RAM does the machine have?

**Comment by robinjugas** [comment]
Thanks for response. 24 GB of RAM. 

[flye.log](https://github.com/fenderglass/Flye/files/2977139/flye.log)

**Comment by mikolmogorov** [comment]
Hi,

Based on the log file, the machine had 24G RAM, but only 11Gb were available. You most likely need more for a 30Mb genome.

I've also recently pushed an update into the 'flye' branch that should reduce memory usage during the consensus/polishing steps - you can try it as well.

**Comment by robinjugas** [comment]
Thank you. I'll try solutions offered by you. Thanks again. I'll reply how I ended.

**Comment by robinjugas** [comment]
I finally had a time and tried the bioconda version with higher RAM and it worked. Thank you for your work & support.
