### ISSUE TITLE
FastaError: Fastq format error

### ISSUE THREAD

**Issue by emmannaemeka** [fenderglass/ABruijn#89]
I tried running Flye on a raw Nanopore read fastq format but keep having this error 
[2019-03-16 11:11:22] INFO: Running Flye 2.3.7-release
[2019-03-16 11:11:22] INFO: Configuring run
Traceback (most recent call last):
  File "/usr/local/bin/flye", line 31, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/flye/main.py", line 506, in main
    _run(args)
  File "/usr/local/lib/python2.7/site-packages/flye/main.py", line 337, in _run
    jobs[i].run()
  File "/usr/local/lib/python2.7/site-packages/flye/main.py", line 82, in run
    params = setup_params(self.args)
  File "/usr/local/lib/python2.7/site-packages/flye/config/configurator.py", line 25, in setup_params
    for seq, seq_len in fp.read_sequence_lengths(read_file).iteritems():
  File "/usr/local/lib/python2.7/site-packages/flye/utils/fasta_parser.py", line 70, in read_sequence_lengths
    for hdr, seq, qual in _read_fastq(handle):
  File "/usr/local/lib/python2.7/site-packages/flye/utils/fasta_parser.py", line 141, in _read_fastq
    raise FastaError("Fastq format error")
flye.utils.fasta_parser.FastaError: Fastq format error

**Comment by mikolmogorov** [comment]
Looks like there a format error in the fastq file. Please try the latest 2.4.1 version, it will tell you the location of formatting error, so you will be able to fix it.

**Comment by emmannaemeka** [comment]
[2019-03-16 19:47:01] INFO: Starting Flye 2.4.1-release
[2019-03-16 19:47:01] INFO: >>>STAGE: configure
[2019-03-16 19:47:01] INFO: Configuring run
[2019-03-16 19:47:01] ERROR: Fastq format error: /Users/emmannaemeka/Desktop/.....fastq at line 0

**Comment by mikolmogorov** [comment]
Yes, something is wrong with the fastq file starting from the very beginning.

**Comment by mikolmogorov** [comment]
Closing this for now - I assume the issue was resolved. Feel free to reopen if it remains.
